// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWatchdogProcessFactory creates a new instance of MockWatchdogProcessFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchdogProcessFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchdogProcessFactory {
	mock := &MockWatchdogProcessFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatchdogProcessFactory is an autogenerated mock type for the WatchdogProcessFactory type
type MockWatchdogProcessFactory struct {
	mock.Mock
}

type MockWatchdogProcessFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchdogProcessFactory) EXPECT() *MockWatchdogProcessFactory_Expecter {
	return &MockWatchdogProcessFactory_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockWatchdogProcessFactory
func (_mock *MockWatchdogProcessFactory) Create() (entities.Mode, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entities.Mode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (entities.Mode, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() entities.Mode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Mode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWatchdogProcessFactory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWatchdogProcessFactory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
func (_e *MockWatchdogProcessFactory_Expecter) Create() *MockWatchdogProcessFactory_Create_Call {
	return &MockWatchdogProcessFactory_Create_Call{Call: _e.mock.On("Create")}
}

func (_c *MockWatchdogProcessFactory_Create_Call) Run(run func()) *MockWatchdogProcessFactory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatchdogProcessFactory_Create_Call) Return(mode entities.Mode, err error) *MockWatchdogProcessFactory_Create_Call {
	_c.Call.Return(mode, err)
	return _c
}

func (_c *MockWatchdogProcessFactory_Create_Call) RunAndReturn(run func() (entities.Mode, error)) *MockWatchdogProcessFactory_Create_Call {
	_c.Call.Return(run)
	return _c
}
