classdef DefaultCapturedEventProviderTest < matlab.mock.TestCase
    %DefaultCapturedEventProviderTest Tests for DefaultCapturedEventProvider

    % Copyright 2026 The MathWorks, Inc.

    methods (Access = private)
        function [mockFactory, mockCollector, collectorBehavior] = createMocks(testCase)
            import matlab.mock.actions.AssignOutputs

            [mockCollector, collectorBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.capture.CollectorFacade, ...
                Strict=true ...
            );

            when( ...
                collectorBehavior.Events().withExactInputs(), ...
                AssignOutputs(struct('type', {}, 'payload', {})) ...
            );

            [mockFactory, factoryBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.capture.CollectorFactoryFacade, ...
                Strict=true ...
            );

            when( ...
                factoryBehavior.EventsCollector().withExactInputs(), ...
                AssignOutputs(mockCollector) ...
            );
        end
    end

    methods (Test)
        function testDefaultCapturedEventProvider_Constructor_HappyPath(testCase)
            % Arrange
            [mockFactory, ~, ~] = testCase.createMocks();

            % Act
            provider = mcpserver.internal.capture.DefaultCapturedEventProvider( ...
                Factory=mockFactory ...
            );

            % Assert
            testCase.verifyInstanceOf( ...
                provider, ...
                ?mcpserver.internal.capture.CapturedEventProvider, ...
                "DefaultCapturedEventProvider should implement CapturedEventProvider" ...
            );

            delete(provider);
        end

        function testDefaultCapturedEventProvider_GetEvents_HappyPath(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            expectedEvents = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockFactory, ~, collectorBehavior] = testCase.createMocks();
            when( ...
                collectorBehavior.Events().withExactInputs(), ...
                AssignOutputs(expectedEvents) ...
            );

            provider = mcpserver.internal.capture.DefaultCapturedEventProvider( ...
                Factory=mockFactory ...
            );

            % Act
            result = provider.getEvents();

            % Assert
            testCase.verifyEqual(result, expectedEvents, ...
                "Should return events from the collector facade" ...
            );

            delete(provider);
        end

        function testDefaultCapturedEventProvider_GetEvents_MultipleEvents(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            expectedEvents = struct( ...
                'type', {'stdout', 'stderr', 'stdout'}, ...
                'payload', {'line1', 'err', 'line2'} ...
            );
            [mockFactory, ~, collectorBehavior] = testCase.createMocks();
            when( ...
                collectorBehavior.Events().withExactInputs(), ...
                AssignOutputs(expectedEvents) ...
            );

            provider = mcpserver.internal.capture.DefaultCapturedEventProvider( ...
                Factory=mockFactory ...
            );

            % Act
            result = provider.getEvents();

            % Assert
            testCase.verifyEqual(numel(result), 3, ...
                "Should return all events from the collector" ...
            );

            delete(provider);
        end

        function testDefaultCapturedEventProvider_GetEvents_EmptyEvents(testCase)
            % Arrange
            [mockFactory, ~, ~] = testCase.createMocks();

            provider = mcpserver.internal.capture.DefaultCapturedEventProvider( ...
                Factory=mockFactory ...
            );

            % Act
            result = provider.getEvents();

            % Assert
            testCase.verifyEmpty(result, ...
                "Should return empty when no events collected" ...
            );

            delete(provider);
        end

        function testDefaultCapturedEventProvider_IsCapturedEventProvider(testCase)
            % Arrange
            [mockFactory, ~, ~] = testCase.createMocks();

            % Act
            provider = mcpserver.internal.capture.DefaultCapturedEventProvider( ...
                Factory=mockFactory ...
            );

            % Assert
            testCase.verifyInstanceOf( ...
                provider, ...
                ?mcpserver.internal.capture.CapturedEventProvider, ...
                "DefaultCapturedEventProvider should implement CapturedEventProvider" ...
            );

            delete(provider);
        end
    end

end
