// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABStartingDirSelector creates a new instance of MockMATLABStartingDirSelector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABStartingDirSelector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABStartingDirSelector {
	mock := &MockMATLABStartingDirSelector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABStartingDirSelector is an autogenerated mock type for the MATLABStartingDirSelector type
type MockMATLABStartingDirSelector struct {
	mock.Mock
}

type MockMATLABStartingDirSelector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABStartingDirSelector) EXPECT() *MockMATLABStartingDirSelector_Expecter {
	return &MockMATLABStartingDirSelector_Expecter{mock: &_m.Mock}
}

// SelectMatlabStartingDir provides a mock function for the type MockMATLABStartingDirSelector
func (_mock *MockMATLABStartingDirSelector) SelectMatlabStartingDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SelectMatlabStartingDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABStartingDirSelector_SelectMatlabStartingDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectMatlabStartingDir'
type MockMATLABStartingDirSelector_SelectMatlabStartingDir_Call struct {
	*mock.Call
}

// SelectMatlabStartingDir is a helper method to define mock.On call
func (_e *MockMATLABStartingDirSelector_Expecter) SelectMatlabStartingDir() *MockMATLABStartingDirSelector_SelectMatlabStartingDir_Call {
	return &MockMATLABStartingDirSelector_SelectMatlabStartingDir_Call{Call: _e.mock.On("SelectMatlabStartingDir")}
}

func (_c *MockMATLABStartingDirSelector_SelectMatlabStartingDir_Call) Run(run func()) *MockMATLABStartingDirSelector_SelectMatlabStartingDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMATLABStartingDirSelector_SelectMatlabStartingDir_Call) Return(s string, err error) *MockMATLABStartingDirSelector_SelectMatlabStartingDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMATLABStartingDirSelector_SelectMatlabStartingDir_Call) RunAndReturn(run func() (string, error)) *MockMATLABStartingDirSelector_SelectMatlabStartingDir_Call {
	_c.Call.Return(run)
	return _c
}
