# Copyright 2025 The MathWorks, Inc.
version: "2"

linters:
  default: standard
  enable:
    - revive # Comprehensive Go linter with extensive rules
    - gosec # Security scanner for Go code
    - govet # Go static analyzer for common errors
    - usetesting #  Static analysis for testing best practices
    - testifylint # Linter for testify assertions and mocking
    - unused
    - inamedparam
    - gochecknoglobals
    - misspell
    - tagalign
    - errcheck
    - bodyclose
    - staticcheck
    - nolintlint
    - iface
    - gomodguard
    - testableexamples
  disable:
    # Maybe enable
    - tagliatelle
    - thelper
    - ireturn
    - exhaustruct
    - lll
    # Actually disable these ones
    - depguard
    - wsl
    - wrapcheck
    - paralleltest
    - nlreturn
    - godot
  settings:
    gomodguard:
      allowed:
        domains:
          - golang.org
          - github.com/google/jsonschema-go
          - github.com/modelcontextprotocol
          - github.com/stretchr/testify
          - github.com/google/uuid
          - github.com/spf13/pflag
    nolintlint:
      require-explanation: true
    revive:
      rules:
        # Disable check which requires all packages exports to have documenting string 
        - name: exported
          disabled: true
    usetesting:
      context-background: true
      os-temp-dir: true
  exclusions:
    generated: lax
    rules:
      # Allow underscores in test function names specifically
      - path: tests/
        linters:
          - revive
        text: "don't use underscores in Go names; method Test"

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-same-issues: 0
  max-issues-per-linter: 0

run:
  relative-path-mode: gomod
