# Copyright 2025-2026 The MathWorks, Inc.

all: true
filename: "{{.InterfaceName}}.go"
log-level: error
pkgname: "mocks"
packages:
    github.com/matlab/matlab-mcp-server/internal:
        config:
            dir: 'mocks/{{.InterfaceDirRelative | trimPrefix "internal" }}'
            recursive: true
            all: true
    github.com/matlab/matlab-mcp-server/internal/messages:
        config:
            all: false
    github.com/matlab/matlab-mcp-server/tests/testutils:
        config:
            dir: 'tests/mocks/{{.InterfaceDirRelative | trimPrefix "tests" }}'
            recursive: true
            all: true
