// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// Getppid provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Getppid() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Getppid")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockOSLayer_Getppid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getppid'
type MockOSLayer_Getppid_Call struct {
	*mock.Call
}

// Getppid is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) Getppid() *MockOSLayer_Getppid_Call {
	return &MockOSLayer_Getppid_Call{Call: _e.mock.On("Getppid")}
}

func (_c *MockOSLayer_Getppid_Call) Run(run func()) *MockOSLayer_Getppid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_Getppid_Call) Return(n int) *MockOSLayer_Getppid_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockOSLayer_Getppid_Call) RunAndReturn(run func() int) *MockOSLayer_Getppid_Call {
	_c.Call.Return(run)
	return _c
}

// Stderr provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Stderr() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stderr")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockOSLayer_Stderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stderr'
type MockOSLayer_Stderr_Call struct {
	*mock.Call
}

// Stderr is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) Stderr() *MockOSLayer_Stderr_Call {
	return &MockOSLayer_Stderr_Call{Call: _e.mock.On("Stderr")}
}

func (_c *MockOSLayer_Stderr_Call) Run(run func()) *MockOSLayer_Stderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_Stderr_Call) Return(writer io.Writer) *MockOSLayer_Stderr_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockOSLayer_Stderr_Call) RunAndReturn(run func() io.Writer) *MockOSLayer_Stderr_Call {
	_c.Call.Return(run)
	return _c
}

// Stdin provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Stdin() io.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdin")
	}

	var r0 io.Reader
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	return r0
}

// MockOSLayer_Stdin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdin'
type MockOSLayer_Stdin_Call struct {
	*mock.Call
}

// Stdin is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) Stdin() *MockOSLayer_Stdin_Call {
	return &MockOSLayer_Stdin_Call{Call: _e.mock.On("Stdin")}
}

func (_c *MockOSLayer_Stdin_Call) Run(run func()) *MockOSLayer_Stdin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_Stdin_Call) Return(reader io.Reader) *MockOSLayer_Stdin_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *MockOSLayer_Stdin_Call) RunAndReturn(run func() io.Reader) *MockOSLayer_Stdin_Call {
	_c.Call.Return(run)
	return _c
}

// Stdout provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Stdout() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdout")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockOSLayer_Stdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdout'
type MockOSLayer_Stdout_Call struct {
	*mock.Call
}

// Stdout is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) Stdout() *MockOSLayer_Stdout_Call {
	return &MockOSLayer_Stdout_Call{Call: _e.mock.On("Stdout")}
}

func (_c *MockOSLayer_Stdout_Call) Run(run func()) *MockOSLayer_Stdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_Stdout_Call) Return(writer io.Writer) *MockOSLayer_Stdout_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockOSLayer_Stdout_Call) RunAndReturn(run func() io.Writer) *MockOSLayer_Stdout_Call {
	_c.Call.Return(run)
	return _c
}
