// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerHandler creates a new instance of MockServerHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerHandler {
	mock := &MockServerHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerHandler is an autogenerated mock type for the ServerHandler type
type MockServerHandler struct {
	mock.Mock
}

type MockServerHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerHandler) EXPECT() *MockServerHandler_Expecter {
	return &MockServerHandler_Expecter{mock: &_m.Mock}
}

// RegisterShutdownFunction provides a mock function for the type MockServerHandler
func (_mock *MockServerHandler) RegisterShutdownFunction(fn func()) {
	_mock.Called(fn)
	return
}

// MockServerHandler_RegisterShutdownFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterShutdownFunction'
type MockServerHandler_RegisterShutdownFunction_Call struct {
	*mock.Call
}

// RegisterShutdownFunction is a helper method to define mock.On call
//   - fn func()
func (_e *MockServerHandler_Expecter) RegisterShutdownFunction(fn interface{}) *MockServerHandler_RegisterShutdownFunction_Call {
	return &MockServerHandler_RegisterShutdownFunction_Call{Call: _e.mock.On("RegisterShutdownFunction", fn)}
}

func (_c *MockServerHandler_RegisterShutdownFunction_Call) Run(run func(fn func())) *MockServerHandler_RegisterShutdownFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func()
		if args[0] != nil {
			arg0 = args[0].(func())
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerHandler_RegisterShutdownFunction_Call) Return() *MockServerHandler_RegisterShutdownFunction_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerHandler_RegisterShutdownFunction_Call) RunAndReturn(run func(fn func())) *MockServerHandler_RegisterShutdownFunction_Call {
	_c.Run(run)
	return _c
}

// TerminateAllProcesses provides a mock function for the type MockServerHandler
func (_mock *MockServerHandler) TerminateAllProcesses() {
	_mock.Called()
	return
}

// MockServerHandler_TerminateAllProcesses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TerminateAllProcesses'
type MockServerHandler_TerminateAllProcesses_Call struct {
	*mock.Call
}

// TerminateAllProcesses is a helper method to define mock.On call
func (_e *MockServerHandler_Expecter) TerminateAllProcesses() *MockServerHandler_TerminateAllProcesses_Call {
	return &MockServerHandler_TerminateAllProcesses_Call{Call: _e.mock.On("TerminateAllProcesses")}
}

func (_c *MockServerHandler_TerminateAllProcesses_Call) Run(run func()) *MockServerHandler_TerminateAllProcesses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerHandler_TerminateAllProcesses_Call) Return() *MockServerHandler_TerminateAllProcesses_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerHandler_TerminateAllProcesses_Call) RunAndReturn(run func()) *MockServerHandler_TerminateAllProcesses_Call {
	_c.Run(run)
	return _c
}
