// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransportFactory creates a new instance of MockTransportFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransportFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransportFactory {
	mock := &MockTransportFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransportFactory is an autogenerated mock type for the TransportFactory type
type MockTransportFactory struct {
	mock.Mock
}

type MockTransportFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransportFactory) EXPECT() *MockTransportFactory_Expecter {
	return &MockTransportFactory_Expecter{mock: &_m.Mock}
}

// NewReceiver provides a mock function for the type MockTransportFactory
func (_mock *MockTransportFactory) NewReceiver(osStdio entities.OSStdio) (transport.Receiver, error) {
	ret := _mock.Called(osStdio)

	if len(ret) == 0 {
		panic("no return value specified for NewReceiver")
	}

	var r0 transport.Receiver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.OSStdio) (transport.Receiver, error)); ok {
		return returnFunc(osStdio)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.OSStdio) transport.Receiver); ok {
		r0 = returnFunc(osStdio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transport.Receiver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(entities.OSStdio) error); ok {
		r1 = returnFunc(osStdio)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransportFactory_NewReceiver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewReceiver'
type MockTransportFactory_NewReceiver_Call struct {
	*mock.Call
}

// NewReceiver is a helper method to define mock.On call
//   - osStdio entities.OSStdio
func (_e *MockTransportFactory_Expecter) NewReceiver(osStdio interface{}) *MockTransportFactory_NewReceiver_Call {
	return &MockTransportFactory_NewReceiver_Call{Call: _e.mock.On("NewReceiver", osStdio)}
}

func (_c *MockTransportFactory_NewReceiver_Call) Run(run func(osStdio entities.OSStdio)) *MockTransportFactory_NewReceiver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.OSStdio
		if args[0] != nil {
			arg0 = args[0].(entities.OSStdio)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransportFactory_NewReceiver_Call) Return(receiver transport.Receiver, err error) *MockTransportFactory_NewReceiver_Call {
	_c.Call.Return(receiver, err)
	return _c
}

func (_c *MockTransportFactory_NewReceiver_Call) RunAndReturn(run func(osStdio entities.OSStdio) (transport.Receiver, error)) *MockTransportFactory_NewReceiver_Call {
	_c.Call.Return(run)
	return _c
}
