classdef DefaultSecureGeneratorTest < matlab.mock.TestCase
    %DefaultSecureGeneratorTest Tests for DefaultSecureGenerator
    %   This test class verifies that DefaultSecureGenerator correctly
    %   generates cryptographically secure keys using OS-level CSPRNGs.
    %   All system calls are mocked via facades.

    % Copyright 2026 The MathWorks, Inc.

    properties (Constant, Access = private)
        ExpectedKeySize(1,1) uint8 = 24
    end

    methods (Test)
        function testDefaultSecureGenerator_Constructor_HappyPath(testCase)
            % Arrange
            [mockOSFacade, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockDotNetFacade, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );

            % Act
            generator = mcpserver.internal.connector.internal.apikeymanager.internal.securegen.DefaultSecureGenerator( ...
                OSFacade=mockOSFacade, ...
                FSFacade=mockFSFacade, ...
                DotNetFacade=mockDotNetFacade ...
            );

            % Assert
            testCase.verifyInstanceOf( ...
                generator, ...
                ?mcpserver.internal.connector.internal.apikeymanager.internal.securegen.SecureGenerator, ...
                "DefaultSecureGenerator should be a SecureGenerator" ...
            );
        end

        function testDefaultSecureGenerator_GenerateKey_MacOS_ReadsFromDevUrandom(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );

            expectedBytes = uint8(0:23);
            expectedKey = lower(strjoin(string(dec2hex(expectedBytes, 2)), ""));
            fid = 42;

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                osBehavior.ismac().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                fsBehavior.fopen(fullfile("/", "dev", "urandom"), "r"), ...
                AssignOutputs(fid) ...
            );
            when( ...
                fsBehavior.fread(fid, testCase.ExpectedKeySize, "*uint8"), ...
                AssignOutputs(expectedBytes) ...
            );
            when( ...
                fsBehavior.fclose(fid), ...
                DoNothing ...
            );

            generator = testCase.createGenerator(mockOSFacade, mockFSFacade);

            % Act
            key = generator.generateKey();

            % Assert
            testCase.verifyEqual(key, expectedKey, ...
                "Key should be hex-encoded bytes from /dev/urandom");
        end

        function testDefaultSecureGenerator_GenerateKey_Linux_ReadsFromDevUrandom(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );

            expectedBytes = uint8(100:123);
            expectedKey = lower(strjoin(string(dec2hex(expectedBytes, 2)), ""));
            fid = 7;

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                osBehavior.ismac().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                osBehavior.isunix().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                fsBehavior.fopen(fullfile("/", "dev", "urandom"), "r"), ...
                AssignOutputs(fid) ...
            );
            when( ...
                fsBehavior.fread(fid, testCase.ExpectedKeySize, "*uint8"), ...
                AssignOutputs(expectedBytes) ...
            );
            when( ...
                fsBehavior.fclose(fid), ...
                DoNothing ...
            );

            generator = testCase.createGenerator(mockOSFacade, mockFSFacade);

            % Act
            key = generator.generateKey();

            % Assert
            testCase.verifyEqual(key, expectedKey, ...
                "Key should be hex-encoded bytes from /dev/urandom");
        end

        function testDefaultSecureGenerator_GenerateKey_Unix_FopenFails_ThrowsError(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );

            expectedError = mcpserver.internal.error.Errors.SecureKeyGenerationFailed();

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                osBehavior.ismac().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                fsBehavior.fopen(fullfile("/", "dev", "urandom"), "r"), ...
                AssignOutputs(-1) ...
            );

            generator = testCase.createGenerator(mockOSFacade, mockFSFacade);

            % Act & Assert
            testCase.verifyError(@() generator.generateKey(), expectedError.identifier);
        end

        function testDefaultSecureGenerator_GenerateKey_Windows_ProducesCorrectHexKey(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockDotNetFacade, dotNetBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );

            expectedBytes = uint8(0:23);
            expectedKey = lower(strjoin(string(dec2hex(expectedBytes, 2)), ""));
            mockRng = struct( ...
                Dispose=@() [], ...
                GetBytes=@(~) [] ...
            );

            when( ...
                dotNetBehavior.createRandomNumberGenerator().withExactInputs(), ...
                AssignOutputs(mockRng) ...
            );
            when( ...
                dotNetBehavior.createByteArray(testCase.ExpectedKeySize), ...
                AssignOutputs(expectedBytes) ...
            );

            generator = mcpserver.internal.connector.internal.apikeymanager.internal.securegen.DefaultSecureGenerator( ...
                OSFacade=mockOSFacade, ...
                FSFacade=mockFSFacade, ...
                DotNetFacade=mockDotNetFacade ...
            );

            % Act
            key = generator.generateKey();

            % Assert
            testCase.verifyEqual(key, expectedKey, ...
                "Key should be hex-encoded bytes from .NET RNG");
        end

        function testDefaultSecureGenerator_GenerateKey_UnsupportedOS_ThrowsError(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockFSFacade, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );

            expectedError = mcpserver.internal.error.Errors.UnsupportedOS();

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                osBehavior.ismac().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                osBehavior.isunix().withExactInputs(), ...
                AssignOutputs(false) ...
            );

            generator = testCase.createGenerator(mockOSFacade, mockFSFacade);

            % Act & Assert
            testCase.verifyError(@() generator.generateKey(), expectedError.identifier);
        end
    end

    methods (Access = private)
        function generator = createGenerator(~, mockOSFacade, mockFSFacade)
            generator = mcpserver.internal.connector.internal.apikeymanager.internal.securegen.DefaultSecureGenerator( ...
                OSFacade=mockOSFacade, ...
                FSFacade=mockFSFacade ...
            );
        end
    end

end
