// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransportFactory creates a new instance of MockTransportFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransportFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransportFactory {
	mock := &MockTransportFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransportFactory is an autogenerated mock type for the TransportFactory type
type MockTransportFactory struct {
	mock.Mock
}

type MockTransportFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransportFactory) EXPECT() *MockTransportFactory_Expecter {
	return &MockTransportFactory_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function for the type MockTransportFactory
func (_mock *MockTransportFactory) NewClient(subProcessStdio entities.SubProcessStdio) (transport.Client, error) {
	ret := _mock.Called(subProcessStdio)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 transport.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.SubProcessStdio) (transport.Client, error)); ok {
		return returnFunc(subProcessStdio)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.SubProcessStdio) transport.Client); ok {
		r0 = returnFunc(subProcessStdio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transport.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(entities.SubProcessStdio) error); ok {
		r1 = returnFunc(subProcessStdio)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransportFactory_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type MockTransportFactory_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - subProcessStdio entities.SubProcessStdio
func (_e *MockTransportFactory_Expecter) NewClient(subProcessStdio interface{}) *MockTransportFactory_NewClient_Call {
	return &MockTransportFactory_NewClient_Call{Call: _e.mock.On("NewClient", subProcessStdio)}
}

func (_c *MockTransportFactory_NewClient_Call) Run(run func(subProcessStdio entities.SubProcessStdio)) *MockTransportFactory_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.SubProcessStdio
		if args[0] != nil {
			arg0 = args[0].(entities.SubProcessStdio)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransportFactory_NewClient_Call) Return(client transport.Client, err error) *MockTransportFactory_NewClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockTransportFactory_NewClient_Call) RunAndReturn(run func(subProcessStdio entities.SubProcessStdio) (transport.Client, error)) *MockTransportFactory_NewClient_Call {
	_c.Call.Return(run)
	return _c
}
