// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWatchdogProcess creates a new instance of MockWatchdogProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchdogProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchdogProcess {
	mock := &MockWatchdogProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatchdogProcess is an autogenerated mock type for the WatchdogProcess type
type MockWatchdogProcess struct {
	mock.Mock
}

type MockWatchdogProcess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchdogProcess) EXPECT() *MockWatchdogProcess_Expecter {
	return &MockWatchdogProcess_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockWatchdogProcess
func (_mock *MockWatchdogProcess) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWatchdogProcess_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockWatchdogProcess_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockWatchdogProcess_Expecter) Start() *MockWatchdogProcess_Start_Call {
	return &MockWatchdogProcess_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockWatchdogProcess_Start_Call) Run(run func()) *MockWatchdogProcess_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatchdogProcess_Start_Call) Return(err error) *MockWatchdogProcess_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWatchdogProcess_Start_Call) RunAndReturn(run func() error) *MockWatchdogProcess_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stdio provides a mock function for the type MockWatchdogProcess
func (_mock *MockWatchdogProcess) Stdio() entities.SubProcessStdio {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdio")
	}

	var r0 entities.SubProcessStdio
	if returnFunc, ok := ret.Get(0).(func() entities.SubProcessStdio); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.SubProcessStdio)
		}
	}
	return r0
}

// MockWatchdogProcess_Stdio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdio'
type MockWatchdogProcess_Stdio_Call struct {
	*mock.Call
}

// Stdio is a helper method to define mock.On call
func (_e *MockWatchdogProcess_Expecter) Stdio() *MockWatchdogProcess_Stdio_Call {
	return &MockWatchdogProcess_Stdio_Call{Call: _e.mock.On("Stdio")}
}

func (_c *MockWatchdogProcess_Stdio_Call) Run(run func()) *MockWatchdogProcess_Stdio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatchdogProcess_Stdio_Call) Return(subProcessStdio entities.SubProcessStdio) *MockWatchdogProcess_Stdio_Call {
	_c.Call.Return(subProcessStdio)
	return _c
}

func (_c *MockWatchdogProcess_Stdio_Call) RunAndReturn(run func() entities.SubProcessStdio) *MockWatchdogProcess_Stdio_Call {
	_c.Call.Return(run)
	return _c
}
