classdef CoreDotNetAccessControlTest < matlab.mock.TestCase
    %CoreDotNetAccessControlTest Unit tests for CoreDotNetAccessControl

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testCoreDotNetAccessControl_Constructor_HappyPath(testCase)
            % Arrange
            [mockFacade, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );

            % Act
            obj = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.CoreDotNetAccessControl( ...
                DotNetFacade=mockFacade);

            % Assert
            testCase.verifyInstanceOf( ...
                obj, ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl ...
            );
        end

        function testCoreDotNetAccessControl_SetAccessControl_LoadsAssemblyAndDelegatesToFacade(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );

            mockTarget = struct(FullName="C:\test");
            mockSecurity = struct(Sddl="D:P");

            when( ...
                behavior.addAssembly("System.IO.FileSystem.AccessControl"), ...
                AssignOutputs([]) ...
            );
            when( ...
                behavior.setFileSystemAccessControl(mockTarget, mockSecurity), ...
                DoNothing ...
            );

            obj = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.CoreDotNetAccessControl( ...
                DotNetFacade=mockFacade);

            % Act
            obj.setAccessControl(mockTarget, mockSecurity);

            % Assert
            testCase.verifyCalled(behavior.addAssembly("System.IO.FileSystem.AccessControl"));
            testCase.verifyCalled(behavior.setFileSystemAccessControl(mockTarget, mockSecurity));
        end

        function testCoreDotNetAccessControl_SetAccessControl_CalledTwice_LoadsAssemblyOnlyOnce(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing
            import matlab.mock.actions.ThrowException

            [mockFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );

            mockTarget = struct(FullName="C:\test");
            mockSecurity = struct(Sddl="D:P");

            when( ...
                behavior.addAssembly("System.IO.FileSystem.AccessControl"), ...
                AssignOutputs([]).then( ...
                    ThrowException(MException("TEST:unexpected", "Should not be called again"))) ...
            );
            when( ...
                behavior.setFileSystemAccessControl(mockTarget, mockSecurity), ...
                DoNothing ...
            );

            obj = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.CoreDotNetAccessControl( ...
                DotNetFacade=mockFacade);

            % Act & Assert
            obj.setAccessControl(mockTarget, mockSecurity);
            obj.setAccessControl(mockTarget, mockSecurity);
        end

        function testCoreDotNetAccessControl_SetAccessControl_AssemblyLoadFails_ThrowsError(testCase)
            % Arrange
            import matlab.mock.actions.ThrowException

            [mockFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );

            expectedError = mcpserver.internal.error.Errors.FailedToLoadDotNetAssembly( ...
                "System.IO.FileSystem.AccessControl");

            when( ...
                behavior.addAssembly("System.IO.FileSystem.AccessControl"), ...
                ThrowException(MException("NET:loadError", "Assembly not found")) ...
            );

            obj = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.CoreDotNetAccessControl( ...
                DotNetFacade=mockFacade);

            mockTarget = struct(FullName="C:\test");
            mockSecurity = struct(Sddl="D:P");

            % Act & Assert
            testCase.verifyError( ...
                @() obj.setAccessControl(mockTarget, mockSecurity), ...
                expectedError.identifier ...
            );
        end
    end

end
