classdef CreateDotNetAccessControlTest < matlab.mock.TestCase
    %CreateDotNetAccessControlTest Unit tests for createDotNetAccessControl factory

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testCreateDotNetAccessControl_CoreRuntime_ReturnsCoreStrategy(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockDotNetFacade, dotNetBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                dotNetBehavior.getDotNetRuntime().withExactInputs(), ...
                AssignOutputs("core") ...
            );

            % Act
            strategy = mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.createDotNetAccessControl( ...
                OSFacade=mockOSFacade, ...
                DotNetFacade=mockDotNetFacade);

            % Assert
            testCase.verifyInstanceOf(strategy, ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.CoreDotNetAccessControl);
        end

        function testCreateDotNetAccessControl_FrameworkRuntime_ReturnsFrameworkStrategy(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockDotNetFacade, dotNetBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                dotNetBehavior.getDotNetRuntime().withExactInputs(), ...
                AssignOutputs("framework") ...
            );

            % Act
            strategy = mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.createDotNetAccessControl( ...
                OSFacade=mockOSFacade, ...
                DotNetFacade=mockDotNetFacade);

            % Assert
            testCase.verifyInstanceOf(strategy, ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.FrameworkDotNetAccessControl);
        end

        function testCreateDotNetAccessControl_UnknownRuntime_DefaultsToCoreStrategy(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockDotNetFacade, dotNetBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                dotNetBehavior.getDotNetRuntime().withExactInputs(), ...
                AssignOutputs("something-else") ...
            );

            % Act
            strategy = mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.createDotNetAccessControl( ...
                OSFacade=mockOSFacade, ...
                DotNetFacade=mockDotNetFacade);

            % Assert
            testCase.verifyInstanceOf(strategy, ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.CoreDotNetAccessControl);
        end

        function testCreateDotNetAccessControl_NonWindows_ReturnsCoreStrategy(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOSFacade, osBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            [mockDotNetFacade, ~] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );

            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );

            % Act
            strategy = mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.createDotNetAccessControl( ...
                OSFacade=mockOSFacade, ...
                DotNetFacade=mockDotNetFacade);

            % Assert
            testCase.verifyInstanceOf(strategy, ...
                ?mcpcoreserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.CoreDotNetAccessControl);
        end
    end

end
