classdef DefaultEventPollerTest < matlab.mock.TestCase
    %DefaultEventPollerTest Tests for mcpcoreserver.internal.capture.DefaultEventPoller

    % Copyright 2026 The MathWorks, Inc.

    methods (Access = private)
        function [mockFactory, mockTimer, timerBehavior] = createMockTimerFactory(testCase)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockTimer, timerBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.timer.TimerFacade, ...
                Strict=true ...
            );

            when( ...
                timerBehavior.Start().withExactInputs(), ...
                DoNothing ...
            );
            when( ...
                timerBehavior.Stop().withExactInputs(), ...
                DoNothing ...
            );

            [mockFactory, factoryBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.timer.TimerFactoryFacade, ...
                Strict=true ...
            );

            when( ...
                withAnyInputs(factoryBehavior.timer), ...
                AssignOutputs(mockTimer) ...
            );
        end

        function [mockSource, sourceBehavior] = createMockEventSource(testCase, eventsToReturn)
            import matlab.mock.actions.AssignOutputs

            [mockSource, sourceBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.capture.CapturedEventProvider, ...
                Strict=true ...
            );

            when( ...
                sourceBehavior.getEvents().withExactInputs(), ...
                AssignOutputs(eventsToReturn) ...
            );
        end

        function [mockDisplayer, displayerBehavior] = createMockDisplayer(testCase)
            import matlab.mock.actions.DoNothing

            [mockDisplayer, displayerBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.display.console.EventDisplayer, ...
                Strict=true ...
            );

            when( ...
                withAnyInputs(displayerBehavior.displayEvents), ...
                DoNothing ...
            );
        end
    end

    methods (Test)
        function testDefaultEventPoller_Constructor_CreatesTimer(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockTimer, timerBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.timer.TimerFacade, ...
                Strict=true ...
            );
            when( ...
                timerBehavior.Start().withExactInputs(), ...
                DoNothing ...
            );
            when( ...
                timerBehavior.Stop().withExactInputs(), ...
                DoNothing ...
            );

            [mockFactory, factoryBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.timer.TimerFactoryFacade, ...
                Strict=true ...
            );
            when( ...
                withAnyInputs(factoryBehavior.timer), ...
                AssignOutputs(mockTimer) ...
            );

            events = struct('type', {}, 'payload', {});
            [mockSource, ~] = testCase.createMockEventSource(events);
            [mockDisplayer, ~] = testCase.createMockDisplayer();

            % Act
            poller = mcpcoreserver.internal.capture.DefaultEventPoller( ...
                TimerFactory=mockFactory, ...
                EventSource=mockSource, ...
                Displayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyCalled( ...
                factoryBehavior.timer(0.25, 'fixedRate', 'drop', matlab.unittest.constraints.IsAnything), ...
                "timer factory should be called with period=0.25, fixedRate, drop" ...
            );

            delete(poller);
        end

        function testDefaultEventPoller_Start_StartsTimer(testCase)
            % Arrange
            [mockFactory, ~, timerBehavior] = testCase.createMockTimerFactory();
            events = struct('type', {}, 'payload', {});
            [mockSource, ~] = testCase.createMockEventSource(events);
            [mockDisplayer, ~] = testCase.createMockDisplayer();

            poller = mcpcoreserver.internal.capture.DefaultEventPoller( ...
                TimerFactory=mockFactory, ...
                EventSource=mockSource, ...
                Displayer=mockDisplayer ...
            );

            % Act
            poller.start();

            % Assert
            testCase.verifyCalled( ...
                timerBehavior.Start().withExactInputs(), ...
                "start should call TimerFacade.Start()" ...
            );

            delete(poller);
        end

        function testDefaultEventPoller_Stop_StopsTimer(testCase)
            % Arrange
            [mockFactory, ~, timerBehavior] = testCase.createMockTimerFactory();
            events = struct('type', {}, 'payload', {});
            [mockSource, ~] = testCase.createMockEventSource(events);
            [mockDisplayer, ~] = testCase.createMockDisplayer();

            poller = mcpcoreserver.internal.capture.DefaultEventPoller( ...
                TimerFactory=mockFactory, ...
                EventSource=mockSource, ...
                Displayer=mockDisplayer ...
            );

            % Act
            poller.stop();

            % Assert
            testCase.verifyCalled( ...
                timerBehavior.Stop().withExactInputs(), ...
                "stop should call TimerFacade.Stop()" ...
            );

            delete(poller);
        end

        function testDefaultEventPoller_Flush_NewEvents_DisplaysOnlyNew(testCase)
            % Arrange
            events = struct('type', {'stdout', 'stdout', 'stdout'}, ...
                'payload', {'hello', ' ', 'world'});

            [mockFactory, ~, ~] = testCase.createMockTimerFactory();
            [mockSource, ~] = testCase.createMockEventSource(events);
            [mockDisplayer, displayerBehavior] = testCase.createMockDisplayer();

            poller = mcpcoreserver.internal.capture.DefaultEventPoller( ...
                TimerFactory=mockFactory, ...
                EventSource=mockSource, ...
                Displayer=mockDisplayer ...
            );

            % Act
            poller.flush();

            % Assert
            testCase.verifyCalled( ...
                displayerBehavior.displayEvents(events), ...
                "displayEvents should be called with all new events" ...
            );

            delete(poller);
        end

        function testDefaultEventPoller_Flush_NoNewEvents_DoesNotCallDisplayer(testCase)
            % Arrange
            events = struct('type', {}, 'payload', {});

            [mockFactory, ~, ~] = testCase.createMockTimerFactory();
            [mockSource, ~] = testCase.createMockEventSource(events);
            [mockDisplayer, displayerBehavior] = testCase.createMockDisplayer();

            poller = mcpcoreserver.internal.capture.DefaultEventPoller( ...
                TimerFactory=mockFactory, ...
                EventSource=mockSource, ...
                Displayer=mockDisplayer ...
            );

            % Act
            poller.flush();

            % Assert
            testCase.verifyNotCalled( ...
                withAnyInputs(displayerBehavior.displayEvents), ...
                "displayEvents should not be called when there are no events" ...
            );

            delete(poller);
        end

        function testDefaultEventPoller_Flush_SecondFlush_DisplaysOnlyNewEvents(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            firstBatch = struct('type', {'stdout', 'stdout'}, ...
                'payload', {'hello', ' '});
            secondBatch = struct('type', {'stdout', 'stdout', 'stdout'}, ...
                'payload', {'hello', ' ', 'world'});

            [mockFactory, ~, ~] = testCase.createMockTimerFactory();
            [mockSource, sourceBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.capture.CapturedEventProvider, ...
                Strict=true ...
            );
            when( ...
                sourceBehavior.getEvents().withExactInputs(), ...
                AssignOutputs(firstBatch) ...
            );
            [mockDisplayer, displayerBehavior] = testCase.createMockDisplayer();

            poller = mcpcoreserver.internal.capture.DefaultEventPoller( ...
                TimerFactory=mockFactory, ...
                EventSource=mockSource, ...
                Displayer=mockDisplayer ...
            );

            % Act -- first flush (calls getEvents twice: once for events, once for post-display count)
            poller.flush();

            % Reconfigure mock to simulate new events arriving (appended after display artifacts)
            when( ...
                sourceBehavior.getEvents().withExactInputs(), ...
                AssignOutputs(secondBatch) ...
            );
            testCase.clearMockHistory(mockDisplayer);

            % Act -- second flush
            poller.flush();

            % Assert -- only the third event is new (indices 1-2 already displayed in first flush)
            expectedNewEvents = secondBatch(3);
            testCase.verifyCalled( ...
                displayerBehavior.displayEvents(expectedNewEvents), ...
                "Second flush should only display events after LastDisplayedIdx" ...
            );

            % Assert -- getEvents returns all real events from both flushes
            result = poller.getEvents();
            testCase.verifyEqual(numel(result), 3, ...
                "getEvents should return all real events from both flushes" ...
            );

            delete(poller);
        end

        function testDefaultEventPoller_GetEvents_ReturnsRealEventsAfterFlush(testCase)
            % Arrange
            expectedEvents = struct('type', {'stdout'}, 'payload', {'hello'});

            [mockFactory, ~, ~] = testCase.createMockTimerFactory();
            [mockSource, ~] = testCase.createMockEventSource(expectedEvents);
            [mockDisplayer, ~] = testCase.createMockDisplayer();

            poller = mcpcoreserver.internal.capture.DefaultEventPoller( ...
                TimerFactory=mockFactory, ...
                EventSource=mockSource, ...
                Displayer=mockDisplayer ...
            );

            % Act
            poller.flush();
            result = poller.getEvents();

            % Assert
            testCase.verifyEqual(result, expectedEvents, ...
                "getEvents should return events accumulated during flush" ...
            );

            delete(poller);
        end

        function testDefaultEventPoller_GetEvents_EmptyBeforeFlush(testCase)
            % Arrange
            expectedEvents = struct('type', {'stdout'}, 'payload', {'hello'});

            [mockFactory, ~, ~] = testCase.createMockTimerFactory();
            [mockSource, ~] = testCase.createMockEventSource(expectedEvents);
            [mockDisplayer, ~] = testCase.createMockDisplayer();

            poller = mcpcoreserver.internal.capture.DefaultEventPoller( ...
                TimerFactory=mockFactory, ...
                EventSource=mockSource, ...
                Displayer=mockDisplayer ...
            );

            % Act
            result = poller.getEvents();

            % Assert
            testCase.verifyEmpty(result, ...
                "getEvents should return empty before any flush" ...
            );

            delete(poller);
        end

        function testDefaultEventPoller_Delete_StopsTimer(testCase)
            % Arrange
            [mockFactory, ~, timerBehavior] = testCase.createMockTimerFactory();
            events = struct('type', {}, 'payload', {});
            [mockSource, ~] = testCase.createMockEventSource(events);
            [mockDisplayer, ~] = testCase.createMockDisplayer();

            poller = mcpcoreserver.internal.capture.DefaultEventPoller( ...
                TimerFactory=mockFactory, ...
                EventSource=mockSource, ...
                Displayer=mockDisplayer ...
            );

            % Act
            delete(poller);

            % Assert
            testCase.verifyCalled( ...
                timerBehavior.Stop().withExactInputs(), ...
                "delete should stop the timer" ...
            );
        end

        function testDefaultEventPoller_IsEventPoller(testCase)
            % Arrange
            [mockFactory, ~, ~] = testCase.createMockTimerFactory();
            events = struct('type', {}, 'payload', {});
            [mockSource, ~] = testCase.createMockEventSource(events);
            [mockDisplayer, ~] = testCase.createMockDisplayer();

            % Act
            poller = mcpcoreserver.internal.capture.DefaultEventPoller( ...
                TimerFactory=mockFactory, ...
                EventSource=mockSource, ...
                Displayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyTrue( ...
                isa(poller, 'mcpcoreserver.internal.capture.EventPoller'), ...
                "DefaultEventPoller should be an EventPoller" ...
            );
            testCase.verifyTrue( ...
                isa(poller, 'mcpcoreserver.internal.capture.CapturedEventProvider'), ...
                "DefaultEventPoller should be a CapturedEventProvider" ...
            );

            delete(poller);
        end
    end

end
