// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMCPServerConfigurator creates a new instance of MockMCPServerConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMCPServerConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMCPServerConfigurator {
	mock := &MockMCPServerConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMCPServerConfigurator is an autogenerated mock type for the MCPServerConfigurator type
type MockMCPServerConfigurator struct {
	mock.Mock
}

type MockMCPServerConfigurator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMCPServerConfigurator) EXPECT() *MockMCPServerConfigurator_Expecter {
	return &MockMCPServerConfigurator_Expecter{mock: &_m.Mock}
}

// GetToolsToAdd provides a mock function for the type MockMCPServerConfigurator
func (_mock *MockMCPServerConfigurator) GetToolsToAdd() []tools.Tool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetToolsToAdd")
	}

	var r0 []tools.Tool
	if returnFunc, ok := ret.Get(0).(func() []tools.Tool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tools.Tool)
		}
	}
	return r0
}

// MockMCPServerConfigurator_GetToolsToAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToolsToAdd'
type MockMCPServerConfigurator_GetToolsToAdd_Call struct {
	*mock.Call
}

// GetToolsToAdd is a helper method to define mock.On call
func (_e *MockMCPServerConfigurator_Expecter) GetToolsToAdd() *MockMCPServerConfigurator_GetToolsToAdd_Call {
	return &MockMCPServerConfigurator_GetToolsToAdd_Call{Call: _e.mock.On("GetToolsToAdd")}
}

func (_c *MockMCPServerConfigurator_GetToolsToAdd_Call) Run(run func()) *MockMCPServerConfigurator_GetToolsToAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMCPServerConfigurator_GetToolsToAdd_Call) Return(tools1 []tools.Tool) *MockMCPServerConfigurator_GetToolsToAdd_Call {
	_c.Call.Return(tools1)
	return _c
}

func (_c *MockMCPServerConfigurator_GetToolsToAdd_Call) RunAndReturn(run func() []tools.Tool) *MockMCPServerConfigurator_GetToolsToAdd_Call {
	_c.Call.Return(run)
	return _c
}
