// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMCPSDKServerFactory creates a new instance of MockMCPSDKServerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMCPSDKServerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMCPSDKServerFactory {
	mock := &MockMCPSDKServerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMCPSDKServerFactory is an autogenerated mock type for the MCPSDKServerFactory type
type MockMCPSDKServerFactory struct {
	mock.Mock
}

type MockMCPSDKServerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMCPSDKServerFactory) EXPECT() *MockMCPSDKServerFactory_Expecter {
	return &MockMCPSDKServerFactory_Expecter{mock: &_m.Mock}
}

// NewServer provides a mock function for the type MockMCPSDKServerFactory
func (_mock *MockMCPSDKServerFactory) NewServer(name string, instructions string) *mcp.Server {
	ret := _mock.Called(name, instructions)

	if len(ret) == 0 {
		panic("no return value specified for NewServer")
	}

	var r0 *mcp.Server
	if returnFunc, ok := ret.Get(0).(func(string, string) *mcp.Server); ok {
		r0 = returnFunc(name, instructions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.Server)
		}
	}
	return r0
}

// MockMCPSDKServerFactory_NewServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewServer'
type MockMCPSDKServerFactory_NewServer_Call struct {
	*mock.Call
}

// NewServer is a helper method to define mock.On call
//   - name string
//   - instructions string
func (_e *MockMCPSDKServerFactory_Expecter) NewServer(name interface{}, instructions interface{}) *MockMCPSDKServerFactory_NewServer_Call {
	return &MockMCPSDKServerFactory_NewServer_Call{Call: _e.mock.On("NewServer", name, instructions)}
}

func (_c *MockMCPSDKServerFactory_NewServer_Call) Run(run func(name string, instructions string)) *MockMCPSDKServerFactory_NewServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMCPSDKServerFactory_NewServer_Call) Return(server *mcp.Server) *MockMCPSDKServerFactory_NewServer_Call {
	_c.Call.Return(server)
	return _c
}

func (_c *MockMCPSDKServerFactory_NewServer_Call) RunAndReturn(run func(name string, instructions string) *mcp.Server) *MockMCPSDKServerFactory_NewServer_Call {
	_c.Call.Return(run)
	return _c
}
