classdef DefaultWindowsACLManagerTest < matlab.mock.TestCase
%DefaultWindowsACLManagerTest Unit tests for DefaultWindowsACLManager

    % Copyright 2026 The MathWorks, Inc.

    properties (Constant, Access = private)
        % Well-known Windows SIDs
        SystemSID = "S-1-5-18"
        AdministratorsSID = "S-1-5-32-544"
        AuthenticatedUsersSID = "S-1-5-11"

        % Fake user SID for test identity
        TestUserSID = "S-1-5-21-111-222-333-1001"
        TestUserLongSID = "S-1-5-21-1234567890-1234567890-1234567890-1001"
    end

    methods (Test)
        function testDefaultWindowsACLManager_GetCurrentUserSID_ReturnsSIDFromIdentity(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, ~] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );

            mockIdentity = testCase.createMockIdentity(testCase.TestUserLongSID);
            when( ...
                facadeBehavior.getCurrentWindowsIdentity().withExactInputs(), ...
                AssignOutputs(mockIdentity) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            sid = manager.getCurrentUserSID();

            % Assert
            testCase.verifyEqual(sid, testCase.TestUserLongSID);
        end

        function testDefaultWindowsACLManager_GetCurrentUserSID_CachesResult(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, ~] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );

            mockIdentity = testCase.createMockIdentity(testCase.TestUserSID);
            when( ...
                facadeBehavior.getCurrentWindowsIdentity().withExactInputs(), ...
                AssignOutputs(mockIdentity) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            sid1 = manager.getCurrentUserSID();
            sid2 = manager.getCurrentUserSID();

            % Assert
            testCase.verifyEqual(sid1, sid2);
            testCase.assertCalled( ...
                facadeBehavior.getCurrentWindowsIdentity().withExactInputs(), ...
                "Should only call getCurrentWindowsIdentity once (cached)" ...
            );
        end

        function testDefaultWindowsACLManager_GetAllowedSIDs_Directory_ReturnsAllowSIDsOnly(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, ~] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );

            tempFixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testFolder = tempFixture.Folder;

            when( ...
                facadeBehavior.getAccessSectionsAccess().withExactInputs(), ...
                AssignOutputs("AccessSections.Access") ...
            );
            when( ...
                facadeBehavior.getAllowAccessControlType().withExactInputs(), ...
                AssignOutputs("Allow") ...
            );

            mockIdentity = testCase.createMockIdentity(testCase.TestUserSID);
            when( ...
                facadeBehavior.getCurrentWindowsIdentity().withExactInputs(), ...
                AssignOutputs(mockIdentity) ...
            );

            systemSID = testCase.SystemSID;
            adminsSID = testCase.AdministratorsSID;
            authUsersSID = testCase.AuthenticatedUsersSID;
            rules = testCase.createMockRules([
                struct(AccessControlType="Allow", IdentityReference=struct(ToString=@() systemSID)), ...
                struct(AccessControlType="Deny", IdentityReference=struct(ToString=@() authUsersSID)), ...
                struct(AccessControlType="Allow", IdentityReference=struct(ToString=@() adminsSID))
            ]);
            mockSecurity = testCase.createMockSecurity(rules);
            when( ...
                facadeBehavior.DirectorySecurity(testFolder, "AccessSections.Access"), ...
                AssignOutputs(mockSecurity) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            sids = manager.getAllowedSIDs(testFolder);

            % Assert
            testCase.verifyEqual(sids, [testCase.SystemSID, testCase.AdministratorsSID]);
        end

        function testDefaultWindowsACLManager_GetAllowedSIDs_File_UsesFileSecurity(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, ~] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );

            tempFixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testFile = fullfile(tempFixture.Folder, "test.txt");
            writelines("test", testFile);

            when( ...
                facadeBehavior.getAccessSectionsAccess().withExactInputs(), ...
                AssignOutputs("AccessSections.Access") ...
            );
            when( ...
                facadeBehavior.getAllowAccessControlType().withExactInputs(), ...
                AssignOutputs("Allow") ...
            );

            mockIdentity = testCase.createMockIdentity(testCase.TestUserSID);
            when( ...
                facadeBehavior.getCurrentWindowsIdentity().withExactInputs(), ...
                AssignOutputs(mockIdentity) ...
            );

            systemSID = testCase.SystemSID;
            rules = testCase.createMockRules([
                struct(AccessControlType="Allow", IdentityReference=struct(ToString=@() systemSID))
            ]);
            mockSecurity = testCase.createMockSecurity(rules);
            when( ...
                facadeBehavior.FileSecurity(char(testFile), "AccessSections.Access"), ...
                AssignOutputs(mockSecurity) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            sids = manager.getAllowedSIDs(testFile);

            % Assert
            testCase.verifyEqual(sids, testCase.SystemSID);
        end

        function testDefaultWindowsACLManager_GetAllowedSIDs_EmptyRules_ReturnsEmptyArray(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, ~] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );

            tempFixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testFolder = tempFixture.Folder;

            when( ...
                facadeBehavior.getAccessSectionsAccess().withExactInputs(), ...
                AssignOutputs("AccessSections.Access") ...
            );
            when( ...
                facadeBehavior.getAllowAccessControlType().withExactInputs(), ...
                AssignOutputs("Allow") ...
            );

            mockIdentity = testCase.createMockIdentity(testCase.TestUserSID);
            when( ...
                facadeBehavior.getCurrentWindowsIdentity().withExactInputs(), ...
                AssignOutputs(mockIdentity) ...
            );

            rules = struct(Count=0, Item=@(~) []);
            mockSecurity = testCase.createMockSecurity(rules);
            when( ...
                facadeBehavior.DirectorySecurity(testFolder, "AccessSections.Access"), ...
                AssignOutputs(mockSecurity) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            sids = manager.getAllowedSIDs(testFolder);

            % Assert
            testCase.verifyEmpty(sids);
        end

        function testDefaultWindowsACLManager_IsDACLProtected_Directory_ProtectedDACL_ReturnsTrue(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, ~] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );

            tempFixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testFolder = tempFixture.Folder;

            when( ...
                facadeBehavior.getAccessSectionsAccess().withExactInputs(), ...
                AssignOutputs("AccessSections.Access") ...
            );

            mockSecurity = testCase.createMockSecurityWithSddl("D:P(A;OICI;FA;;;S-1-5-18)");
            when( ...
                facadeBehavior.DirectorySecurity(testFolder, "AccessSections.Access"), ...
                AssignOutputs(mockSecurity) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            tf = manager.isDACLProtected(testFolder);

            % Assert
            testCase.verifyTrue(tf);
        end

        function testDefaultWindowsACLManager_IsDACLProtected_Directory_InheritedDACL_ReturnsFalse(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, ~] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );

            tempFixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testFolder = tempFixture.Folder;

            when( ...
                facadeBehavior.getAccessSectionsAccess().withExactInputs(), ...
                AssignOutputs("AccessSections.Access") ...
            );

            mockSecurity = testCase.createMockSecurityWithSddl("D:(A;OICI;FA;;;S-1-5-18)");
            when( ...
                facadeBehavior.DirectorySecurity(testFolder, "AccessSections.Access"), ...
                AssignOutputs(mockSecurity) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            tf = manager.isDACLProtected(testFolder);

            % Assert
            testCase.verifyFalse(tf);
        end

        function testDefaultWindowsACLManager_IsDACLProtected_File_ProtectedDACL_ReturnsTrue(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, ~] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );

            tempFixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testFile = fullfile(tempFixture.Folder, "test.txt");
            writelines("test", testFile);

            when( ...
                facadeBehavior.getAccessSectionsAccess().withExactInputs(), ...
                AssignOutputs("AccessSections.Access") ...
            );

            mockSecurity = testCase.createMockSecurityWithSddl("D:P(A;;FA;;;S-1-5-18)");
            when( ...
                facadeBehavior.FileSecurity(char(testFile), "AccessSections.Access"), ...
                AssignOutputs(mockSecurity) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            tf = manager.isDACLProtected(testFile);

            % Assert
            testCase.verifyTrue(tf);
        end

        function testDefaultWindowsACLManager_SetProtectedACL_Directory_DelegatesWithCorrectObjects(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, accessControlBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );
            when( ...
                withAnyInputs(accessControlBehavior.setAccessControl), ...
                DoNothing ...
            );

            tempFixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testFolder = tempFixture.Folder;

            when( ...
                facadeBehavior.getAccessSectionsAccess().withExactInputs(), ...
                AssignOutputs("AccessSections.Access") ...
            );

            mockSecurity = struct(SetSecurityDescriptorSddlForm=@(~,~) []);
            when( ...
                withAnyInputs(facadeBehavior.DirectorySecurity), ...
                AssignOutputs(mockSecurity) ...
            );

            mockDirInfo = struct(FullName=testFolder);
            when( ...
                facadeBehavior.createDirectoryInfo(testFolder), ...
                AssignOutputs(mockDirInfo) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            manager.setProtectedACL(testFolder, [testCase.SystemSID, testCase.AdministratorsSID], true);

            % Assert
            testCase.verifyCalled(withAnyInputs(facadeBehavior.DirectorySecurity));
            testCase.verifyCalled(facadeBehavior.createDirectoryInfo(testFolder));
            testCase.verifyCalled(withAnyInputs(accessControlBehavior.setAccessControl));
        end

        function testDefaultWindowsACLManager_SetProtectedACL_File_DelegatesWithCorrectObjects(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, accessControlBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );
            when( ...
                withAnyInputs(accessControlBehavior.setAccessControl), ...
                DoNothing ...
            );

            tempFixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testFile = fullfile(tempFixture.Folder, "test.txt");
            writelines("test", testFile);

            when( ...
                facadeBehavior.getAccessSectionsAccess().withExactInputs(), ...
                AssignOutputs("AccessSections.Access") ...
            );

            mockSecurity = struct(SetSecurityDescriptorSddlForm=@(~,~) []);
            when( ...
                withAnyInputs(facadeBehavior.FileSecurity), ...
                AssignOutputs(mockSecurity) ...
            );

            mockFileInfo = struct(FullName=testFile);
            when( ...
                facadeBehavior.createFileInfo(testFile), ...
                AssignOutputs(mockFileInfo) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            manager.setProtectedACL(testFile, testCase.SystemSID, false);

            % Assert
            testCase.verifyCalled(withAnyInputs(facadeBehavior.FileSecurity));
            testCase.verifyCalled(facadeBehavior.createFileInfo(testFile));
            testCase.verifyCalled(withAnyInputs(accessControlBehavior.setAccessControl));
        end

        function testDefaultWindowsACLManager_SetProtectedACL_SingleSID_DelegatesCorrectly(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, accessControlBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );
            when( ...
                withAnyInputs(accessControlBehavior.setAccessControl), ...
                DoNothing ...
            );

            tempFixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testFolder = tempFixture.Folder;

            when( ...
                facadeBehavior.getAccessSectionsAccess().withExactInputs(), ...
                AssignOutputs("AccessSections.Access") ...
            );

            mockSecurity = struct(SetSecurityDescriptorSddlForm=@(~,~) []);
            when( ...
                withAnyInputs(facadeBehavior.DirectorySecurity), ...
                AssignOutputs(mockSecurity) ...
            );

            mockDirInfo = struct(FullName=testFolder);
            when( ...
                facadeBehavior.createDirectoryInfo(testFolder), ...
                AssignOutputs(mockDirInfo) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act
            manager.setProtectedACL(testFolder, testCase.SystemSID, true);

            % Assert
            testCase.verifyCalled(withAnyInputs(accessControlBehavior.setAccessControl));
        end

        function testDefaultWindowsACLManager_SetProtectedACL_StrategyThrows_ErrorPropagates(testCase)
            % Arrange
            import matlab.mock.actions.ThrowException
            import matlab.mock.actions.AssignOutputs

            [mockFacade, facadeBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.dotnet.DotNetFacade, ...
                Strict=true ...
            );
            [mockAccessControl, accessControlBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.internal.dotnet.DotNetAccessControl, ...
                Strict=true ...
            );

            when( ...
                withAnyInputs(accessControlBehavior.setAccessControl), ...
                ThrowException(MException("test:accessDenied", "Access denied")) ...
            );

            tempFixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testFolder = tempFixture.Folder;

            when( ...
                facadeBehavior.getAccessSectionsAccess().withExactInputs(), ...
                AssignOutputs("AccessSections.Access") ...
            );

            mockSecurity = struct(SetSecurityDescriptorSddlForm=@(~,~) []);
            when( ...
                withAnyInputs(facadeBehavior.DirectorySecurity), ...
                AssignOutputs(mockSecurity) ...
            );

            mockDirInfo = struct(FullName=testFolder);
            when( ...
                facadeBehavior.createDirectoryInfo(testFolder), ...
                AssignOutputs(mockDirInfo) ...
            );

            manager = mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.DefaultWindowsACLManager( ...
                DotNetAccessControl=mockAccessControl, ...
                DotNetFacade=mockFacade ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() manager.setProtectedACL(testFolder, [testCase.SystemSID, "SY"], true), ...
                "test:accessDenied");
        end
    end

    methods (Access = private)
        function identity = createMockIdentity(~, sidString)
            identity = struct( ...
                User=struct( ...
                    ToString=@() sidString, ...
                    GetType=@() "System.Security.Principal.SecurityIdentifier" ...
                ) ...
            );
        end

        function rules = createMockRules(~, ruleStructs)
            rules = struct( ...
                Count=numel(ruleStructs), ...
                Item=@(i) ruleStructs(i+1) ...
            );
        end

        function security = createMockSecurity(~, rules)
            security = struct( ...
                GetAccessRules=@(~,~,~) rules ...
            );
        end

        function security = createMockSecurityWithSddl(~, sddlString)
            security = struct( ...
                GetSecurityDescriptorSddlForm=@(~) sddlString ...
            );
        end
    end

end
