classdef Base64PngFigureConverterTest < matlab.mock.TestCase
    %Base64PngFigureConverterTest Unit tests for Base64PngFigureConverter

    % Copyright 2026 The MathWorks, Inc.

    properties (Constant, Access = private)
        FakeAppDataFolder = "/home/user/.MathWorks/MATLABMCPCoreServer"
    end

    methods (Test)
        function testBase64PngFigureConverter_Convert_HappyPath_ReturnsBase64Struct(testCase)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            mocks = testCase.createDefaultMocks();
            expectedFiguresFolder = fullfile(testCase.FakeAppDataFolder, "v1", "figures");
            expectedTmpPath = fullfile(expectedFiguresFolder, "fakepath");
            expectedBytes = uint8([137 80 78 71]);
            expectedB64 = "iVBORw0KGg==";
            fakeFileId = 42;

            when( ...
                mocks.appDataBehavior.getAppDataFolder().withExactInputs(), ...
                AssignOutputs(testCase.FakeAppDataFolder) ...
            );
            when( ...
                mocks.fsAdaptorBehavior.ensureSecureFolder(expectedFiguresFolder), ...
                DoNothing ...
            );
            when( ...
                mocks.exportBehavior.tempname(expectedFiguresFolder), ...
                AssignOutputs(expectedTmpPath) ...
            );
            when( ...
                withAnyInputs(mocks.exportBehavior.exportgraphics), ...
                DoNothing ...
            );
            when( ...
                mocks.exportBehavior.base64encode(expectedBytes), ...
                AssignOutputs(expectedB64) ...
            );
            when( ...
                mocks.fsBehavior.fopen(expectedTmpPath + ".png", 'r'), ...
                AssignOutputs(fakeFileId) ...
            );
            when( ...
                mocks.fsBehavior.fread(fakeFileId, Inf, '*uint8'), ...
                AssignOutputs(expectedBytes) ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.fclose), ...
                DoNothing ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.delete), ...
                DoNothing ...
            );

            converter = testCase.createConverter(mocks);
            evt = struct('type', 'figure', 'payload', 0);

            result = converter.convert(evt);

            testCase.verifyEqual(result.outputType, 'figure');
            testCase.verifyEqual(result.mimeType, 'image/png');
            testCase.verifyEqual(result.data, char(expectedB64));
        end

        function testBase64PngFigureConverter_Convert_EnsuresSecureFiguresFolderUnderAppData(testCase)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            mocks = testCase.createDefaultMocks();
            expectedFiguresFolder = fullfile(testCase.FakeAppDataFolder, "v1", "figures");
            expectedTmpPath = fullfile(expectedFiguresFolder, "fakepath");
            fakeFileId = 42;

            testCase.stubHappyPath(mocks, expectedFiguresFolder, expectedTmpPath, fakeFileId);

            converter = testCase.createConverter(mocks);
            evt = struct('type', 'figure', 'payload', 0);

            converter.convert(evt);

            testCase.verifyCalled( ...
                mocks.fsAdaptorBehavior.ensureSecureFolder(expectedFiguresFolder), ...
                "ensureSecureFolder must be called on <appData>/v1/figures before exportgraphics" ...
            );
            testCase.verifyCalled( ...
                mocks.exportBehavior.tempname(expectedFiguresFolder), ...
                "tempname must be scoped to the secured figures folder" ...
            );
        end

        function testBase64PngFigureConverter_Convert_CallsExportgraphicsWithDefaultResolution(testCase)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            mocks = testCase.createDefaultMocks();
            expectedFiguresFolder = fullfile(testCase.FakeAppDataFolder, "v1", "figures");
            expectedTmpPath = fullfile(expectedFiguresFolder, "fakepath");
            figHandle = 0;
            fakeFileId = 42;

            testCase.stubHappyPath(mocks, expectedFiguresFolder, expectedTmpPath, fakeFileId);

            converter = testCase.createConverter(mocks);
            evt = struct('type', 'figure', 'payload', figHandle);

            converter.convert(evt);

            testCase.verifyCalled( ...
                mocks.exportBehavior.exportgraphics(figHandle, expectedTmpPath + ".png", 'Resolution', 150), ...
                "exportgraphics should be called with Resolution=150 by default" ...
            );
        end

        function testBase64PngFigureConverter_Convert_CustomResolution_CallsExportgraphicsWithCustomValue(testCase)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            mocks = testCase.createDefaultMocks();
            expectedFiguresFolder = fullfile(testCase.FakeAppDataFolder, "v1", "figures");
            expectedTmpPath = fullfile(expectedFiguresFolder, "fakepath");
            figHandle = 0;
            fakeFileId = 42;

            testCase.stubHappyPath(mocks, expectedFiguresFolder, expectedTmpPath, fakeFileId);

            converter = testCase.createConverter(mocks, Resolution=300);
            evt = struct('type', 'figure', 'payload', figHandle);

            converter.convert(evt);

            testCase.verifyCalled( ...
                mocks.exportBehavior.exportgraphics(figHandle, expectedTmpPath + ".png", 'Resolution', 300), ...
                "exportgraphics should be called with custom Resolution=300" ...
            );
        end

        function testBase64PngFigureConverter_Convert_DeletesTempFileViaCleanup(testCase)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            mocks = testCase.createDefaultMocks();
            expectedFiguresFolder = fullfile(testCase.FakeAppDataFolder, "v1", "figures");
            expectedTmpPath = fullfile(expectedFiguresFolder, "fakepath");
            fakeFileId = 42;

            testCase.stubHappyPath(mocks, expectedFiguresFolder, expectedTmpPath, fakeFileId);

            converter = testCase.createConverter(mocks);
            evt = struct('type', 'figure', 'payload', 0);

            converter.convert(evt);

            testCase.verifyCalled( ...
                mocks.fsBehavior.delete(expectedTmpPath + ".png"), ...
                "delete should be called with the temp PNG path" ...
            );
        end

        function testBase64PngFigureConverter_Convert_ExportgraphicsThrows_StillDeletesTempFile(testCase)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing
            import matlab.mock.actions.ThrowException

            mocks = testCase.createDefaultMocks();
            expectedFiguresFolder = fullfile(testCase.FakeAppDataFolder, "v1", "figures");
            expectedTmpPath = fullfile(expectedFiguresFolder, "fakepath");

            when( ...
                mocks.appDataBehavior.getAppDataFolder().withExactInputs(), ...
                AssignOutputs(testCase.FakeAppDataFolder) ...
            );
            when( ...
                mocks.fsAdaptorBehavior.ensureSecureFolder(expectedFiguresFolder), ...
                DoNothing ...
            );
            when( ...
                mocks.exportBehavior.tempname(expectedFiguresFolder), ...
                AssignOutputs(expectedTmpPath) ...
            );
            when( ...
                withAnyInputs(mocks.exportBehavior.exportgraphics), ...
                ThrowException(MException('test:export', 'export failed')) ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.delete), ...
                DoNothing ...
            );

            converter = testCase.createConverter(mocks);
            evt = struct('type', 'figure', 'payload', 0);

            try
                converter.convert(evt);
            catch
            end

            testCase.verifyCalled( ...
                mocks.fsBehavior.delete(expectedTmpPath + ".png"), ...
                "delete should be called even when exportgraphics throws" ...
            );
        end

        function testBase64PngFigureConverter_Convert_FopenFails_ThrowsFailedToReadFile(testCase)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            mocks = testCase.createDefaultMocks();
            expectedFiguresFolder = fullfile(testCase.FakeAppDataFolder, "v1", "figures");
            expectedTmpPath = fullfile(expectedFiguresFolder, "fakepath");

            when( ...
                mocks.appDataBehavior.getAppDataFolder().withExactInputs(), ...
                AssignOutputs(testCase.FakeAppDataFolder) ...
            );
            when( ...
                mocks.fsAdaptorBehavior.ensureSecureFolder(expectedFiguresFolder), ...
                DoNothing ...
            );
            when( ...
                mocks.exportBehavior.tempname(expectedFiguresFolder), ...
                AssignOutputs(expectedTmpPath) ...
            );
            when( ...
                withAnyInputs(mocks.exportBehavior.exportgraphics), ...
                DoNothing ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.fopen), ...
                AssignOutputs(-1) ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.delete), ...
                DoNothing ...
            );

            converter = testCase.createConverter(mocks);
            evt = struct('type', 'figure', 'payload', 0);

            testCase.verifyError( ...
                @() converter.convert(evt), ...
                "mcpcoreserver:FailedToReadFile" ...
            );
        end

        function testBase64PngFigureConverter_Convert_DeleteThrows_SwallowedSilently(testCase)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing
            import matlab.mock.actions.ThrowException

            mocks = testCase.createDefaultMocks();
            expectedFiguresFolder = fullfile(testCase.FakeAppDataFolder, "v1", "figures");
            expectedTmpPath = fullfile(expectedFiguresFolder, "fakepath");
            expectedB64 = "iVBORw0KGg==";
            fakeFileId = 42;

            when( ...
                mocks.appDataBehavior.getAppDataFolder().withExactInputs(), ...
                AssignOutputs(testCase.FakeAppDataFolder) ...
            );
            when( ...
                mocks.fsAdaptorBehavior.ensureSecureFolder(expectedFiguresFolder), ...
                DoNothing ...
            );
            when( ...
                mocks.exportBehavior.tempname(expectedFiguresFolder), ...
                AssignOutputs(expectedTmpPath) ...
            );
            when( ...
                withAnyInputs(mocks.exportBehavior.exportgraphics), ...
                DoNothing ...
            );
            when( ...
                withAnyInputs(mocks.exportBehavior.base64encode), ...
                AssignOutputs(expectedB64) ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.fopen), ...
                AssignOutputs(fakeFileId) ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.fread), ...
                AssignOutputs(uint8([1 2 3])) ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.fclose), ...
                DoNothing ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.delete), ...
                ThrowException(MException('MATLAB:DELETE:FileNotFound', 'file not found')) ...
            );

            converter = testCase.createConverter(mocks);
            evt = struct('type', 'figure', 'payload', 0);

            result = converter.convert(evt);

            testCase.verifyCalled( ...
                mocks.fsBehavior.delete(expectedTmpPath + ".png"), ...
                "delete should be attempted unconditionally" ...
            );
            testCase.verifyEqual(result.data, char(expectedB64), ...
                "convert should still return the encoded payload when delete throws");
        end
    end

    methods (Static, Access = private)
        function converter = createConverter(mocks, options)
            arguments
                mocks
                options.Resolution = []
            end
            args = { ...
                'AppDataLocator', mocks.mockAppData, ...
                'FSAdaptor',      mocks.mockFSAdaptor, ...
                'ExportFacade',   mocks.mockExport, ...
                'FSFacade',       mocks.mockFS ...
            };
            if ~isempty(options.Resolution)
                args = [args, {'Resolution', options.Resolution}];
            end
            converter = mcpcoreserver.internal.output.converter.Base64PngFigureConverter(args{:});
        end
    end

    methods (Access = private)
        function mocks = createDefaultMocks(testCase)
            [mocks.mockAppData, mocks.appDataBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.appdata.AppDataLocator, ...
                Strict=true ...
            );
            [mocks.mockFSAdaptor, mocks.fsAdaptorBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.fs.FSAdaptor, ...
                Strict=true ...
            );
            [mocks.mockExport, mocks.exportBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.export.ExportFacade, ...
                Strict=true ...
            );
            [mocks.mockFS, mocks.fsBehavior] = testCase.createMock( ...
                ?mcpcoreserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
        end

        function stubHappyPath(testCase, mocks, figuresFolder, tmpPath, fakeFileId)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            when( ...
                mocks.appDataBehavior.getAppDataFolder().withExactInputs(), ...
                AssignOutputs(testCase.FakeAppDataFolder) ...
            );
            when( ...
                mocks.fsAdaptorBehavior.ensureSecureFolder(figuresFolder), ...
                DoNothing ...
            );
            when( ...
                mocks.exportBehavior.tempname(figuresFolder), ...
                AssignOutputs(tmpPath) ...
            );
            when( ...
                withAnyInputs(mocks.exportBehavior.exportgraphics), ...
                DoNothing ...
            );
            when( ...
                withAnyInputs(mocks.exportBehavior.base64encode), ...
                AssignOutputs("abc") ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.fopen), ...
                AssignOutputs(fakeFileId) ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.fread), ...
                AssignOutputs(uint8([1 2 3])) ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.fclose), ...
                DoNothing ...
            );
            when( ...
                withAnyInputs(mocks.fsBehavior.delete), ...
                DoNothing ...
            );
        end
    end

end
