classdef evaluateWithCaptureTest < matlab.unittest.TestCase
    %evaluateWithCaptureTest Tests for the public evaluateWithCapture wrapper

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testEvaluateWithCapture_CodeOnly_UsesDefaults(testCase)
            testCase.verifyWarningFree( ...
                @() evaluateWithCapture("x = 1;"), ...
                "evaluateWithCapture should accept code-only with all options defaulting" ...
            );
        end

        function testEvaluateWithCapture_ShowFigureWindows_AcceptsTrue(testCase)
            testCase.verifyWarningFree( ...
                @() evaluateWithCapture("x = 1;", ShowFigureWindows=true), ...
                "evaluateWithCapture should accept ShowFigureWindows=true" ...
            );
        end

        function testEvaluateWithCapture_ShowFigureWindows_AcceptsFalse(testCase)
            testCase.verifyWarningFree( ...
                @() evaluateWithCapture("x = 1;", ShowFigureWindows=false), ...
                "evaluateWithCapture should accept ShowFigureWindows=false" ...
            );
        end

        function testEvaluateWithCapture_DisplayCapturedEvents_AcceptsTrue(testCase)
            testCase.verifyWarningFree( ...
                @() evaluateWithCapture("x = 1;", DisplayCapturedEvents=true), ...
                "evaluateWithCapture should accept DisplayCapturedEvents=true" ...
            );
        end

        function testEvaluateWithCapture_DisplayDuringExecution_AcceptsFalse(testCase)
            testCase.verifyWarningFree( ...
                @() evaluateWithCapture("x = 1;", DisplayDuringExecution=false), ...
                "evaluateWithCapture should accept DisplayDuringExecution=false" ...
            );
        end

        function testEvaluateWithCapture_AllOptions_Combined(testCase)
            testCase.verifyWarningFree( ...
                @() evaluateWithCapture("x = 1;", ...
                    ShowFigureWindows=false, ...
                    DisplayCapturedEvents=true, ...
                    DisplayDuringExecution=false), ...
                "evaluateWithCapture should accept all options combined" ...
            );
        end

        function testEvaluateWithCapture_InvalidCodeType_Errors(testCase)
            testCase.verifyError( ...
                @() evaluateWithCapture(struct()), ...
                "MATLAB:validation:UnableToConvert", ...
                "evaluateWithCapture should error when code is not a string" ...
            );
        end

        function testEvaluateWithCapture_InvalidShowFigureWindowsType_Errors(testCase)
            testCase.verifyError( ...
                @() evaluateWithCapture("x = 1;", ShowFigureWindows="notlogical"), ...
                "MATLAB:validation:UnableToConvert", ...
                "evaluateWithCapture should error when ShowFigureWindows is not logical" ...
            );
        end

        function testEvaluateWithCapture_InvalidDisplayCapturedEventsType_Errors(testCase)
            testCase.verifyError( ...
                @() evaluateWithCapture("x = 1;", DisplayCapturedEvents="notlogical"), ...
                "MATLAB:validation:UnableToConvert", ...
                "evaluateWithCapture should error when DisplayCapturedEvents is not logical" ...
            );
        end

        function testEvaluateWithCapture_InvalidDisplayDuringExecutionType_Errors(testCase)
            testCase.verifyError( ...
                @() evaluateWithCapture("x = 1;", DisplayDuringExecution="notlogical"), ...
                "MATLAB:validation:UnableToConvert", ...
                "evaluateWithCapture should error when DisplayDuringExecution is not logical" ...
            );
        end

        function testEvaluateWithCapture_NoArguments_Errors(testCase)
            testCase.verifyError( ...
                @() evaluateWithCapture(), ...
                "MATLAB:minrhs", ...
                "evaluateWithCapture should error when called with no arguments" ...
            );
        end

        function testEvaluateWithCapture_ReturnsResults(testCase)
            results = evaluateWithCapture("disp('hello')", DisplayDuringExecution=false);

            testCase.verifyClass(results, 'cell', ...
                "evaluateWithCapture should return results as a cell array" ...
            );
            testCase.verifyNotEmpty(results, ...
                "evaluateWithCapture should return non-empty results for code that produces output" ...
            );
            result = results{1};
            testCase.verifyTrue(isstruct(result), ...
                "Each result element should be a struct" ...
            );
            testCase.verifyEqual(result.outputType, 'consoleOutput', ...
                "stdout should produce a consoleOutput result" ...
            );
            testCase.verifySubstring(result.text, 'hello', ...
                "Result text should contain the displayed value" ...
            );
        end
    end

end
