classdef DefaultAppDataLocatorTest < matlab.mock.TestCase
    %DefaultAppDataLocatorTest Tests for DefaultAppDataLocator
    %   This test class verifies that DefaultAppDataLocator correctly
    %   returns platform-specific application data folder paths.

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testDefaultAppDataLocator_Constructor_HappyPath(testCase)
            % Arrange
            [mockOS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            % Act
            locator = mcpserver.internal.appdata.DefaultAppDataLocator( ...
                OSFacade=mockOS ...
            );

            % Assert
            testCase.verifyInstanceOf(locator, ?mcpserver.internal.appdata.AppDataLocator, ...
                "DefaultAppDataLocator should be an AppDataLocator");
        end

        function testDefaultAppDataLocator_GetAppDataFolder_HappyPath_Linux(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOS, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedHome = fullfile("home", "user");

            when( ...
                behavior.ismac().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                behavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                behavior.isunix().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                behavior.getenv("HOME"), ...
                AssignOutputs(expectedHome) ...
            );

            locator = mcpserver.internal.appdata.DefaultAppDataLocator( ...
                OSFacade=mockOS ...
            );

            % Act
            path = locator.getAppDataFolder();

            % Assert
            expectedPath = fullfile(expectedHome, ".MathWorks", "MATLABMCPServer");
            testCase.verifyEqual(path, expectedPath, ...
                "Linux path should be HOME/.MathWorks/MATLABMCPServer");
        end

        function testDefaultAppDataLocator_GetAppDataFolder_HappyPath_Darwin(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOS, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedHome = fullfile("Users", "username");

            when( ...
                behavior.ismac().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                behavior.getenv("HOME"), ...
                AssignOutputs(expectedHome) ...
            );

            locator = mcpserver.internal.appdata.DefaultAppDataLocator( ...
                OSFacade=mockOS ...
            );

            % Act
            path = locator.getAppDataFolder();

            % Assert
            expectedPath = fullfile(expectedHome, "Library", "Application Support", "MathWorks", "MATLAB MCP Server");
            testCase.verifyEqual(path, expectedPath, ...
                "macOS path should be HOME/Library/Application Support/MathWorks/MATLAB MCP Server");
        end

        function testDefaultAppDataLocator_GetAppDataFolder_HappyPath_Windows(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOS, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedAppData = fullfile("C:", "Users", "username", "AppData", "Roaming");

            when( ...
                behavior.ismac().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                behavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                behavior.getenv("APPDATA"), ...
                AssignOutputs(expectedAppData) ...
            );

            locator = mcpserver.internal.appdata.DefaultAppDataLocator( ...
                OSFacade=mockOS ...
            );

            % Act
            path = locator.getAppDataFolder();

            % Assert
            expectedPath = fullfile(expectedAppData, "MathWorks", "MATLAB MCP Server");
            testCase.verifyEqual(path, expectedPath, ...
                "Windows path should be APPDATA/MathWorks/MATLAB MCP Server");
        end

        function testDefaultAppDataLocator_GetAppDataFolder_Linux_MissingHomeEnvVar(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOS, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            when( ...
                behavior.ismac().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                behavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                behavior.isunix().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                behavior.getenv("HOME"), ...
                AssignOutputs("") ...
            );

            locator = mcpserver.internal.appdata.DefaultAppDataLocator( ...
                OSFacade=mockOS ...
            );

            expectedError = mcpserver.internal.error.Errors.MissingEnvironmentVariable("HOME");

            % Act & Assert
            testCase.verifyError(@() locator.getAppDataFolder(), ...
                expectedError.identifier, ...
                "Missing HOME environment variable should throw MissingEnvironmentVariable error");
        end

        function testDefaultAppDataLocator_GetAppDataFolder_Darwin_MissingHomeEnvVar(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOS, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            when( ...
                behavior.ismac().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                behavior.getenv("HOME"), ...
                AssignOutputs("") ...
            );

            locator = mcpserver.internal.appdata.DefaultAppDataLocator( ...
                OSFacade=mockOS ...
            );

            expectedError = mcpserver.internal.error.Errors.MissingEnvironmentVariable("HOME");

            % Act & Assert
            testCase.verifyError(@() locator.getAppDataFolder(), ...
                expectedError.identifier, ...
                "Missing HOME environment variable should throw MissingEnvironmentVariable error");
        end

        function testDefaultAppDataLocator_GetAppDataFolder_Windows_MissingAppDataEnvVar(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOS, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            when( ...
                behavior.ismac().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                behavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );
            when( ...
                behavior.getenv("APPDATA"), ...
                AssignOutputs("") ...
            );

            locator = mcpserver.internal.appdata.DefaultAppDataLocator( ...
                OSFacade=mockOS ...
            );

            expectedError = mcpserver.internal.error.Errors.MissingEnvironmentVariable("APPDATA");

            % Act & Assert
            testCase.verifyError(@() locator.getAppDataFolder(), ...
                expectedError.identifier, ...
                "Missing APPDATA environment variable should throw MissingEnvironmentVariable error");
        end

        function testDefaultAppDataLocator_GetAppDataFolder_UnsupportedOS(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockOS, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            when( ...
                behavior.ismac().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                behavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );
            when( ...
                behavior.isunix().withExactInputs(), ...
                AssignOutputs(false) ...
            );

            locator = mcpserver.internal.appdata.DefaultAppDataLocator( ...
                OSFacade=mockOS ...
            );

            expectedError = mcpserver.internal.error.Errors.UnsupportedOS();

            % Act & Assert
            testCase.verifyError(@() locator.getAppDataFolder(), ...
                expectedError.identifier, ...
                "Unknown OS should throw UnsupportedOS error");
        end
    end

end
