// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// RecordToLogger provides a mock function for the type MockConfig
func (_mock *MockConfig) RecordToLogger(logger entities.Logger) {
	_mock.Called(logger)
	return
}

// MockConfig_RecordToLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordToLogger'
type MockConfig_RecordToLogger_Call struct {
	*mock.Call
}

// RecordToLogger is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockConfig_Expecter) RecordToLogger(logger interface{}) *MockConfig_RecordToLogger_Call {
	return &MockConfig_RecordToLogger_Call{Call: _e.mock.On("RecordToLogger", logger)}
}

func (_c *MockConfig_RecordToLogger_Call) Run(run func(logger entities.Logger)) *MockConfig_RecordToLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_RecordToLogger_Call) Return() *MockConfig_RecordToLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfig_RecordToLogger_Call) RunAndReturn(run func(logger entities.Logger)) *MockConfig_RecordToLogger_Call {
	_c.Run(run)
	return _c
}

// UseSingleMATLABSession provides a mock function for the type MockConfig
func (_mock *MockConfig) UseSingleMATLABSession() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UseSingleMATLABSession")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_UseSingleMATLABSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseSingleMATLABSession'
type MockConfig_UseSingleMATLABSession_Call struct {
	*mock.Call
}

// UseSingleMATLABSession is a helper method to define mock.On call
func (_e *MockConfig_Expecter) UseSingleMATLABSession() *MockConfig_UseSingleMATLABSession_Call {
	return &MockConfig_UseSingleMATLABSession_Call{Call: _e.mock.On("UseSingleMATLABSession")}
}

func (_c *MockConfig_UseSingleMATLABSession_Call) Run(run func()) *MockConfig_UseSingleMATLABSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_UseSingleMATLABSession_Call) Return(b bool) *MockConfig_UseSingleMATLABSession_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_UseSingleMATLABSession_Call) RunAndReturn(run func() bool) *MockConfig_UseSingleMATLABSession_Call {
	_c.Call.Return(run)
	return _c
}
