// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGlobalMATLAB creates a new instance of MockGlobalMATLAB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGlobalMATLAB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGlobalMATLAB {
	mock := &MockGlobalMATLAB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGlobalMATLAB is an autogenerated mock type for the GlobalMATLAB type
type MockGlobalMATLAB struct {
	mock.Mock
}

type MockGlobalMATLAB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGlobalMATLAB) EXPECT() *MockGlobalMATLAB_Expecter {
	return &MockGlobalMATLAB_Expecter{mock: &_m.Mock}
}

// Initialize provides a mock function for the type MockGlobalMATLAB
func (_mock *MockGlobalMATLAB) Initialize(ctx context.Context, logger entities.Logger) error {
	ret := _mock.Called(ctx, logger)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger) error); ok {
		r0 = returnFunc(ctx, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGlobalMATLAB_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockGlobalMATLAB_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
func (_e *MockGlobalMATLAB_Expecter) Initialize(ctx interface{}, logger interface{}) *MockGlobalMATLAB_Initialize_Call {
	return &MockGlobalMATLAB_Initialize_Call{Call: _e.mock.On("Initialize", ctx, logger)}
}

func (_c *MockGlobalMATLAB_Initialize_Call) Run(run func(ctx context.Context, logger entities.Logger)) *MockGlobalMATLAB_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGlobalMATLAB_Initialize_Call) Return(err error) *MockGlobalMATLAB_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGlobalMATLAB_Initialize_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger) error) *MockGlobalMATLAB_Initialize_Call {
	_c.Call.Return(run)
	return _c
}
