// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockServer
func (_mock *MockServer) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockServer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockServer_Expecter) Run() *MockServer_Run_Call {
	return &MockServer_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockServer_Run_Call) Run(run func()) *MockServer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServer_Run_Call) Return(err error) *MockServer_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServer_Run_Call) RunAndReturn(run func() error) *MockServer_Run_Call {
	_c.Call.Return(run)
	return _c
}
