// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DebugMessagesC provides a mock function for the type MockClient
func (_mock *MockClient) DebugMessagesC() <-chan string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DebugMessagesC")
	}

	var r0 <-chan string
	if returnFunc, ok := ret.Get(0).(func() <-chan string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}
	return r0
}

// MockClient_DebugMessagesC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugMessagesC'
type MockClient_DebugMessagesC_Call struct {
	*mock.Call
}

// DebugMessagesC is a helper method to define mock.On call
func (_e *MockClient_Expecter) DebugMessagesC() *MockClient_DebugMessagesC_Call {
	return &MockClient_DebugMessagesC_Call{Call: _e.mock.On("DebugMessagesC")}
}

func (_c *MockClient_DebugMessagesC_Call) Run(run func()) *MockClient_DebugMessagesC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_DebugMessagesC_Call) Return(stringCh <-chan string) *MockClient_DebugMessagesC_Call {
	_c.Call.Return(stringCh)
	return _c
}

func (_c *MockClient_DebugMessagesC_Call) RunAndReturn(run func() <-chan string) *MockClient_DebugMessagesC_Call {
	_c.Call.Return(run)
	return _c
}

// ErrorMessagesC provides a mock function for the type MockClient
func (_mock *MockClient) ErrorMessagesC() <-chan string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrorMessagesC")
	}

	var r0 <-chan string
	if returnFunc, ok := ret.Get(0).(func() <-chan string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}
	return r0
}

// MockClient_ErrorMessagesC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorMessagesC'
type MockClient_ErrorMessagesC_Call struct {
	*mock.Call
}

// ErrorMessagesC is a helper method to define mock.On call
func (_e *MockClient_Expecter) ErrorMessagesC() *MockClient_ErrorMessagesC_Call {
	return &MockClient_ErrorMessagesC_Call{Call: _e.mock.On("ErrorMessagesC")}
}

func (_c *MockClient_ErrorMessagesC_Call) Run(run func()) *MockClient_ErrorMessagesC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ErrorMessagesC_Call) Return(stringCh <-chan string) *MockClient_ErrorMessagesC_Call {
	_c.Call.Return(stringCh)
	return _c
}

func (_c *MockClient_ErrorMessagesC_Call) RunAndReturn(run func() <-chan string) *MockClient_ErrorMessagesC_Call {
	_c.Call.Return(run)
	return _c
}

// SendProcessPID provides a mock function for the type MockClient
func (_mock *MockClient) SendProcessPID(processPID int) error {
	ret := _mock.Called(processPID)

	if len(ret) == 0 {
		panic("no return value specified for SendProcessPID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(processPID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SendProcessPID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendProcessPID'
type MockClient_SendProcessPID_Call struct {
	*mock.Call
}

// SendProcessPID is a helper method to define mock.On call
//   - processPID int
func (_e *MockClient_Expecter) SendProcessPID(processPID interface{}) *MockClient_SendProcessPID_Call {
	return &MockClient_SendProcessPID_Call{Call: _e.mock.On("SendProcessPID", processPID)}
}

func (_c *MockClient_SendProcessPID_Call) Run(run func(processPID int)) *MockClient_SendProcessPID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_SendProcessPID_Call) Return(err error) *MockClient_SendProcessPID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SendProcessPID_Call) RunAndReturn(run func(processPID int) error) *MockClient_SendProcessPID_Call {
	_c.Call.Return(run)
	return _c
}

// SendStop provides a mock function for the type MockClient
func (_mock *MockClient) SendStop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendStop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SendStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStop'
type MockClient_SendStop_Call struct {
	*mock.Call
}

// SendStop is a helper method to define mock.On call
func (_e *MockClient_Expecter) SendStop() *MockClient_SendStop_Call {
	return &MockClient_SendStop_Call{Call: _e.mock.On("SendStop")}
}

func (_c *MockClient_SendStop_Call) Run(run func()) *MockClient_SendStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_SendStop_Call) Return(err error) *MockClient_SendStop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SendStop_Call) RunAndReturn(run func() error) *MockClient_SendStop_Call {
	_c.Call.Return(run)
	return _c
}
