// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessage creates a new instance of MockMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessage {
	mock := &MockMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessage is an autogenerated mock type for the Message type
type MockMessage struct {
	mock.Mock
}

type MockMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessage) EXPECT() *MockMessage_Expecter {
	return &MockMessage_Expecter{mock: &_m.Mock}
}

// seal provides a mock function for the type MockMessage
func (_mock *MockMessage) seal() {
	_mock.Called()
	return
}

// MockMessage_seal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'seal'
type MockMessage_seal_Call struct {
	*mock.Call
}

// seal is a helper method to define mock.On call
func (_e *MockMessage_Expecter) seal() *MockMessage_seal_Call {
	return &MockMessage_seal_Call{Call: _e.mock.On("seal")}
}

func (_c *MockMessage_seal_Call) Run(run func()) *MockMessage_seal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_seal_Call) Return() *MockMessage_seal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMessage_seal_Call) RunAndReturn(run func()) *MockMessage_seal_Call {
	_c.Run(run)
	return _c
}
