// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSStdio creates a new instance of MockOSStdio. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSStdio(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSStdio {
	mock := &MockOSStdio{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSStdio is an autogenerated mock type for the OSStdio type
type MockOSStdio struct {
	mock.Mock
}

type MockOSStdio_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSStdio) EXPECT() *MockOSStdio_Expecter {
	return &MockOSStdio_Expecter{mock: &_m.Mock}
}

// Stderr provides a mock function for the type MockOSStdio
func (_mock *MockOSStdio) Stderr() entities.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stderr")
	}

	var r0 entities.Writer
	if returnFunc, ok := ret.Get(0).(func() entities.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Writer)
		}
	}
	return r0
}

// MockOSStdio_Stderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stderr'
type MockOSStdio_Stderr_Call struct {
	*mock.Call
}

// Stderr is a helper method to define mock.On call
func (_e *MockOSStdio_Expecter) Stderr() *MockOSStdio_Stderr_Call {
	return &MockOSStdio_Stderr_Call{Call: _e.mock.On("Stderr")}
}

func (_c *MockOSStdio_Stderr_Call) Run(run func()) *MockOSStdio_Stderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSStdio_Stderr_Call) Return(writer entities.Writer) *MockOSStdio_Stderr_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockOSStdio_Stderr_Call) RunAndReturn(run func() entities.Writer) *MockOSStdio_Stderr_Call {
	_c.Call.Return(run)
	return _c
}

// Stdin provides a mock function for the type MockOSStdio
func (_mock *MockOSStdio) Stdin() entities.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdin")
	}

	var r0 entities.Reader
	if returnFunc, ok := ret.Get(0).(func() entities.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Reader)
		}
	}
	return r0
}

// MockOSStdio_Stdin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdin'
type MockOSStdio_Stdin_Call struct {
	*mock.Call
}

// Stdin is a helper method to define mock.On call
func (_e *MockOSStdio_Expecter) Stdin() *MockOSStdio_Stdin_Call {
	return &MockOSStdio_Stdin_Call{Call: _e.mock.On("Stdin")}
}

func (_c *MockOSStdio_Stdin_Call) Run(run func()) *MockOSStdio_Stdin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSStdio_Stdin_Call) Return(reader entities.Reader) *MockOSStdio_Stdin_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *MockOSStdio_Stdin_Call) RunAndReturn(run func() entities.Reader) *MockOSStdio_Stdin_Call {
	_c.Call.Return(run)
	return _c
}

// Stdout provides a mock function for the type MockOSStdio
func (_mock *MockOSStdio) Stdout() entities.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdout")
	}

	var r0 entities.Writer
	if returnFunc, ok := ret.Get(0).(func() entities.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Writer)
		}
	}
	return r0
}

// MockOSStdio_Stdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdout'
type MockOSStdio_Stdout_Call struct {
	*mock.Call
}

// Stdout is a helper method to define mock.On call
func (_e *MockOSStdio_Expecter) Stdout() *MockOSStdio_Stdout_Call {
	return &MockOSStdio_Stdout_Call{Call: _e.mock.On("Stdout")}
}

func (_c *MockOSStdio_Stdout_Call) Run(run func()) *MockOSStdio_Stdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSStdio_Stdout_Call) Return(writer entities.Writer) *MockOSStdio_Stdout_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockOSStdio_Stdout_Call) RunAndReturn(run func() entities.Writer) *MockOSStdio_Stdout_Call {
	_c.Call.Return(run)
	return _c
}
