// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubProcessStdio creates a new instance of MockSubProcessStdio. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubProcessStdio(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubProcessStdio {
	mock := &MockSubProcessStdio{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubProcessStdio is an autogenerated mock type for the SubProcessStdio type
type MockSubProcessStdio struct {
	mock.Mock
}

type MockSubProcessStdio_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubProcessStdio) EXPECT() *MockSubProcessStdio_Expecter {
	return &MockSubProcessStdio_Expecter{mock: &_m.Mock}
}

// Stderr provides a mock function for the type MockSubProcessStdio
func (_mock *MockSubProcessStdio) Stderr() entities.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stderr")
	}

	var r0 entities.Reader
	if returnFunc, ok := ret.Get(0).(func() entities.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Reader)
		}
	}
	return r0
}

// MockSubProcessStdio_Stderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stderr'
type MockSubProcessStdio_Stderr_Call struct {
	*mock.Call
}

// Stderr is a helper method to define mock.On call
func (_e *MockSubProcessStdio_Expecter) Stderr() *MockSubProcessStdio_Stderr_Call {
	return &MockSubProcessStdio_Stderr_Call{Call: _e.mock.On("Stderr")}
}

func (_c *MockSubProcessStdio_Stderr_Call) Run(run func()) *MockSubProcessStdio_Stderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubProcessStdio_Stderr_Call) Return(reader entities.Reader) *MockSubProcessStdio_Stderr_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *MockSubProcessStdio_Stderr_Call) RunAndReturn(run func() entities.Reader) *MockSubProcessStdio_Stderr_Call {
	_c.Call.Return(run)
	return _c
}

// Stdin provides a mock function for the type MockSubProcessStdio
func (_mock *MockSubProcessStdio) Stdin() entities.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdin")
	}

	var r0 entities.Writer
	if returnFunc, ok := ret.Get(0).(func() entities.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Writer)
		}
	}
	return r0
}

// MockSubProcessStdio_Stdin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdin'
type MockSubProcessStdio_Stdin_Call struct {
	*mock.Call
}

// Stdin is a helper method to define mock.On call
func (_e *MockSubProcessStdio_Expecter) Stdin() *MockSubProcessStdio_Stdin_Call {
	return &MockSubProcessStdio_Stdin_Call{Call: _e.mock.On("Stdin")}
}

func (_c *MockSubProcessStdio_Stdin_Call) Run(run func()) *MockSubProcessStdio_Stdin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubProcessStdio_Stdin_Call) Return(writer entities.Writer) *MockSubProcessStdio_Stdin_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockSubProcessStdio_Stdin_Call) RunAndReturn(run func() entities.Writer) *MockSubProcessStdio_Stdin_Call {
	_c.Call.Return(run)
	return _c
}

// Stdout provides a mock function for the type MockSubProcessStdio
func (_mock *MockSubProcessStdio) Stdout() entities.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdout")
	}

	var r0 entities.Reader
	if returnFunc, ok := ret.Get(0).(func() entities.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Reader)
		}
	}
	return r0
}

// MockSubProcessStdio_Stdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdout'
type MockSubProcessStdio_Stdout_Call struct {
	*mock.Call
}

// Stdout is a helper method to define mock.On call
func (_e *MockSubProcessStdio_Expecter) Stdout() *MockSubProcessStdio_Stdout_Call {
	return &MockSubProcessStdio_Stdout_Call{Call: _e.mock.On("Stdout")}
}

func (_c *MockSubProcessStdio_Stdout_Call) Run(run func()) *MockSubProcessStdio_Stdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubProcessStdio_Stdout_Call) Return(reader entities.Reader) *MockSubProcessStdio_Stdout_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *MockSubProcessStdio_Stdout_Call) RunAndReturn(run func() entities.Reader) *MockSubProcessStdio_Stdout_Call {
	_c.Call.Return(run)
	return _c
}
