// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// PreferredMATLABStartingDirectory provides a mock function for the type MockConfig
func (_mock *MockConfig) PreferredMATLABStartingDirectory() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PreferredMATLABStartingDirectory")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_PreferredMATLABStartingDirectory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreferredMATLABStartingDirectory'
type MockConfig_PreferredMATLABStartingDirectory_Call struct {
	*mock.Call
}

// PreferredMATLABStartingDirectory is a helper method to define mock.On call
func (_e *MockConfig_Expecter) PreferredMATLABStartingDirectory() *MockConfig_PreferredMATLABStartingDirectory_Call {
	return &MockConfig_PreferredMATLABStartingDirectory_Call{Call: _e.mock.On("PreferredMATLABStartingDirectory")}
}

func (_c *MockConfig_PreferredMATLABStartingDirectory_Call) Run(run func()) *MockConfig_PreferredMATLABStartingDirectory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_PreferredMATLABStartingDirectory_Call) Return(s string) *MockConfig_PreferredMATLABStartingDirectory_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_PreferredMATLABStartingDirectory_Call) RunAndReturn(run func() string) *MockConfig_PreferredMATLABStartingDirectory_Call {
	_c.Call.Return(run)
	return _c
}
