classdef DefaultFigureVisibilityControllerTest < matlab.mock.TestCase
    %DefaultFigureVisibilityControllerTest Tests for DefaultFigureVisibilityController
    %   This test class verifies that DefaultFigureVisibilityController
    %   correctly controls figure visibility via hide(), show(), and restore().

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testDefaultFigureVisibilityController_Constructor_HappyPath(testCase)
            % Arrange
            [mockDisplayFacade, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.display.DisplayFacade, ...
                Strict=true ...
            );

            % Act
            controller = mcpserver.internal.display.DefaultFigureVisibilityController( ...
                DisplayFacade=mockDisplayFacade ...
            );

            % Assert
            testCase.verifyInstanceOf( ...
                controller, ...
                ?mcpserver.internal.display.FigureVisibilityController, ...
                "DefaultFigureVisibilityController should be a FigureVisibilityController" ...
            );
        end

        function testDefaultFigureVisibilityController_Hide_HappyPath(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockDisplayFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.display.DisplayFacade, ...
                Strict=true ...
            );

            previousVisible = "on";
            previousCreateFcn = "";

            when( ...
                behavior.getRootProperty("DefaultFigureVisible"), ...
                AssignOutputs(previousVisible) ...
            );
            when( ...
                behavior.getRootProperty("DefaultFigureCreateFcn"), ...
                AssignOutputs(previousCreateFcn) ...
            );
            when( ...
                withAnyInputs(behavior.setRootProperty), ...
                DoNothing ...
            );

            controller = mcpserver.internal.display.DefaultFigureVisibilityController( ...
                DisplayFacade=mockDisplayFacade ...
            );

            % Act
            controller.hide();

            % Assert
            testCase.verifyCalled( ...
                behavior.setRootProperty("DefaultFigureVisible", "off"), ...
                "DefaultFigureVisible should be set to 'off'" ...
            );
            testCase.verifyCalled( ...
                withAnyInputs(behavior.setRootProperty), ...
                "setRootProperty should be called for DefaultFigureCreateFcn" ...
            );
        end

        function testDefaultFigureVisibilityController_Show_HappyPath(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockDisplayFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.display.DisplayFacade, ...
                Strict=true ...
            );

            previousVisible = "off";
            previousCreateFcn = @(~, ~) disp("test");

            when( ...
                behavior.getRootProperty("DefaultFigureVisible"), ...
                AssignOutputs(previousVisible) ...
            );
            when( ...
                behavior.getRootProperty("DefaultFigureCreateFcn"), ...
                AssignOutputs(previousCreateFcn) ...
            );
            when( ...
                withAnyInputs(behavior.setRootProperty), ...
                DoNothing ...
            );

            controller = mcpserver.internal.display.DefaultFigureVisibilityController( ...
                DisplayFacade=mockDisplayFacade ...
            );

            % Act
            controller.show();

            % Assert
            testCase.verifyCalled( ...
                behavior.setRootProperty("DefaultFigureVisible", "on"), ...
                "DefaultFigureVisible should be set to 'on'" ...
            );
            testCase.verifyCalled( ...
                behavior.setRootProperty("DefaultFigureCreateFcn", ""), ...
                "DefaultFigureCreateFcn should be cleared" ...
            );
        end

        function testDefaultFigureVisibilityController_Restore_AfterHide_RestoresPreviousState(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockDisplayFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.display.DisplayFacade, ...
                Strict=true ...
            );

            expectedVisible = "on";
            expectedCreateFcn = "";

            when( ...
                behavior.getRootProperty("DefaultFigureVisible"), ...
                AssignOutputs(expectedVisible) ...
            );
            when( ...
                behavior.getRootProperty("DefaultFigureCreateFcn"), ...
                AssignOutputs(expectedCreateFcn) ...
            );
            when( ...
                withAnyInputs(behavior.setRootProperty), ...
                DoNothing ...
            );

            controller = mcpserver.internal.display.DefaultFigureVisibilityController( ...
                DisplayFacade=mockDisplayFacade ...
            );
            controller.hide();

            % Act
            controller.restore();

            % Assert
            testCase.verifyCalled( ...
                behavior.setRootProperty("DefaultFigureVisible", expectedVisible), ...
                "DefaultFigureVisible should be restored to previous value" ...
            );
            testCase.verifyCalled( ...
                behavior.setRootProperty("DefaultFigureCreateFcn", expectedCreateFcn), ...
                "DefaultFigureCreateFcn should be restored to previous value" ...
            );
        end

        function testDefaultFigureVisibilityController_Restore_WithoutPriorSave_IsNoOp(testCase)
            % Arrange
            [mockDisplayFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.display.DisplayFacade, ...
                Strict=true ...
            );

            controller = mcpserver.internal.display.DefaultFigureVisibilityController( ...
                DisplayFacade=mockDisplayFacade ...
            );

            % Act
            controller.restore();

            % Assert
            testCase.verifyNotCalled( ...
                withAnyInputs(behavior.setRootProperty), ...
                "setRootProperty should not be called when no state was saved" ...
            );
        end

        function testDefaultFigureVisibilityController_Restore_AfterShow_RestoresPreviousState(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockDisplayFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.display.DisplayFacade, ...
                Strict=true ...
            );

            expectedVisible = "off";
            expectedCreateFcn = @(~, ~) disp("test");

            when( ...
                behavior.getRootProperty("DefaultFigureVisible"), ...
                AssignOutputs(expectedVisible) ...
            );
            when( ...
                behavior.getRootProperty("DefaultFigureCreateFcn"), ...
                AssignOutputs(expectedCreateFcn) ...
            );
            when( ...
                withAnyInputs(behavior.setRootProperty), ...
                DoNothing ...
            );

            controller = mcpserver.internal.display.DefaultFigureVisibilityController( ...
                DisplayFacade=mockDisplayFacade ...
            );
            controller.show();

            % Act
            controller.restore();

            % Assert
            testCase.verifyCalled( ...
                behavior.setRootProperty("DefaultFigureVisible", expectedVisible), ...
                "DefaultFigureVisible should be restored to previous value" ...
            );
        end

        function testDefaultFigureVisibilityController_Restore_AfterHideThenShow_RestoresOriginalState(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockDisplayFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.display.DisplayFacade, ...
                Strict=true ...
            );

            expectedVisible = "on";
            expectedCreateFcn = "";

            when( ...
                behavior.getRootProperty("DefaultFigureVisible"), ...
                AssignOutputs(expectedVisible) ...
            );
            when( ...
                behavior.getRootProperty("DefaultFigureCreateFcn"), ...
                AssignOutputs(expectedCreateFcn) ...
            );
            when( ...
                withAnyInputs(behavior.setRootProperty), ...
                DoNothing ...
            );

            controller = mcpserver.internal.display.DefaultFigureVisibilityController( ...
                DisplayFacade=mockDisplayFacade ...
            );
            controller.hide();
            controller.show();

            % Act
            controller.restore();

            % Assert
            testCase.verifyCalled( ...
                behavior.setRootProperty("DefaultFigureVisible", expectedVisible), ...
                "DefaultFigureVisible should be restored to the original state before hide(), not the state after hide()" ...
            );
            testCase.verifyCalled( ...
                behavior.setRootProperty("DefaultFigureCreateFcn", expectedCreateFcn), ...
                "DefaultFigureCreateFcn should be restored to the original state before hide(), not the state after hide()" ...
            );
        end

        function testDefaultFigureVisibilityController_DoubleRestore_SecondRestoreIsNoOp(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockDisplayFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.display.DisplayFacade, ...
                Strict=true ...
            );

            expectedVisible = "on";
            expectedCreateFcn = "";

            when( ...
                behavior.getRootProperty("DefaultFigureVisible"), ...
                AssignOutputs(expectedVisible) ...
            );
            when( ...
                behavior.getRootProperty("DefaultFigureCreateFcn"), ...
                AssignOutputs(expectedCreateFcn) ...
            );
            when( ...
                withAnyInputs(behavior.setRootProperty), ...
                DoNothing ...
            );

            controller = mcpserver.internal.display.DefaultFigureVisibilityController( ...
                DisplayFacade=mockDisplayFacade ...
            );
            controller.hide();
            controller.restore();

            % Clear mock interaction history
            testCase.clearMockHistory(mockDisplayFacade);

            % Act — second restore should be a no-op since state was cleared
            controller.restore();

            % Assert — no calls should have been made after clearing history
            testCase.verifyNotCalled( ...
                withAnyInputs(behavior.setRootProperty), ...
                "setRootProperty should not be called on second restore()" ...
            );
            testCase.verifyNotCalled( ...
                withAnyInputs(behavior.getRootProperty), ...
                "getRootProperty should not be called on second restore()" ...
            );
        end

        function testDefaultFigureVisibilityController_Restore_AfterRestoreThenHide_CapturesNewBaseline(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockDisplayFacade, behavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.display.DisplayFacade, ...
                Strict=true ...
            );

            originalVisible = "on";
            originalCreateFcn = "";

            when( ...
                behavior.getRootProperty("DefaultFigureVisible"), ...
                AssignOutputs(originalVisible) ...
            );
            when( ...
                behavior.getRootProperty("DefaultFigureCreateFcn"), ...
                AssignOutputs(originalCreateFcn) ...
            );
            when( ...
                withAnyInputs(behavior.setRootProperty), ...
                DoNothing ...
            );

            controller = mcpserver.internal.display.DefaultFigureVisibilityController( ...
                DisplayFacade=mockDisplayFacade ...
            );

            % First cycle: hide -> restore
            controller.hide();
            controller.restore();

            % Update mock to return new baseline values for the second cycle
            expectedVisible = "off";
            expectedCreateFcn = "someFcn";

            when( ...
                behavior.getRootProperty("DefaultFigureVisible"), ...
                AssignOutputs(expectedVisible) ...
            );
            when( ...
                behavior.getRootProperty("DefaultFigureCreateFcn"), ...
                AssignOutputs(expectedCreateFcn) ...
            );

            % Second cycle: show captures the new baseline
            controller.show();

            % Clear mock history so we only assert on restore() calls
            testCase.clearMockHistory(mockDisplayFacade);

            % Act
            controller.restore();

            % Assert — should restore to the new baseline, not the original
            testCase.verifyCalled( ...
                behavior.setRootProperty("DefaultFigureVisible", expectedVisible), ...
                "DefaultFigureVisible should be restored to the new baseline captured after first restore()" ...
            );
            testCase.verifyCalled( ...
                behavior.setRootProperty("DefaultFigureCreateFcn", expectedCreateFcn), ...
                "DefaultFigureCreateFcn should be restored to the new baseline captured after first restore()" ...
            );
        end
    end

end
