classdef ExceptionReportTest < matlab.unittest.TestCase
    %ExceptionReportTest Tests for mcpserver.internal.error.ExceptionReport

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testStripInternalFrames_RemovesCallerFrame(testCase)
            % Arrange
            report = sprintf([ ...
                'Error using bar (line 2)\n' ...
                'Something broke\n' ...
                'Error in foo (line 5)\n' ...
                '    out = bar(x);\n' ...
                '          ^^^^^^\n' ...
                'Error in myFunction (line 10)\n' ...
                '        evalin(''base'', code);\n' ...
                '        ^^^^^^^^^^^^^^^^^^^^']);
            err = MException('test:err', '%s', report);

            % Act
            result = mcpserver.internal.error.ExceptionReport.stripInternalFrames( ...
                err, "myFunction");

            % Assert
            expected = sprintf([ ...
                'Error using bar (line 2)\n' ...
                'Something broke\n' ...
                'Error in foo (line 5)\n' ...
                '    out = bar(x);\n' ...
                '          ^^^^^^']);
            testCase.verifyEqual(result.message, expected, ...
                "Caller frame and its continuation lines should be stripped");
            testCase.verifyEqual(result.identifier, 'test:err', ...
                "Identifier should be preserved");
        end

        function testStripInternalFrames_NoCallerFrame_ReportUnchanged(testCase)
            % Arrange
            report = sprintf([ ...
                'Error using bar (line 2)\n' ...
                'Something broke\n' ...
                'Error in foo (line 5)\n' ...
                '    out = bar(x);']);
            err = MException('test:err', '%s', report);

            % Act
            result = mcpserver.internal.error.ExceptionReport.stripInternalFrames( ...
                err, "myFunction");

            % Assert
            testCase.verifyEqual(result.message, report, ...
                "Report should be unchanged when caller name is not found");
        end

        function testStripInternalFrames_FullyQualifiedCallerName(testCase)
            % Arrange
            report = sprintf([ ...
                'Error using bar (line 2)\n' ...
                'Something broke\n' ...
                'Error in mcpserver.internal.evaluateWithCapture (line 29)\n' ...
                '        evalin(''base'', code);\n' ...
                '        ^^^^^^^^^^^^^^^^^^^^']);
            err = MException('test:err', '%s', report);

            % Act
            result = mcpserver.internal.error.ExceptionReport.stripInternalFrames( ...
                err, "evaluateWithCapture");

            % Assert
            expected = sprintf([ ...
                'Error using bar (line 2)\n' ...
                'Something broke']);
            testCase.verifyEqual(result.message, expected, ...
                "Should match caller name within fully qualified package path");
        end

        function testStripInternalFrames_PreservesIdentifier(testCase)
            % Arrange
            err = MException('my:custom:id', 'boom');

            % Act
            result = mcpserver.internal.error.ExceptionReport.stripInternalFrames( ...
                err, "someCaller");

            % Assert
            testCase.verifyEqual(result.identifier, 'my:custom:id', ...
                "Identifier should always be preserved");
        end

        function testStripInternalFrames_NoStack_ReturnsMessage(testCase)
            % Arrange
            err = MException('test:err', 'simple error');

            % Act
            result = mcpserver.internal.error.ExceptionReport.stripInternalFrames( ...
                err, "evaluateWithCapture");

            % Assert
            testCase.verifyEqual(result.message, 'simple error', ...
                "Stackless exception should return the original message");
        end

        function testStripInternalFrames_PreservesCauseChain(testCase)
            % Arrange
            cause1 = MException('cause:one', 'first cause');
            cause2 = MException('cause:two', 'second cause');
            err = MException('test:err', 'outer error');
            err = err.addCause(cause1);
            err = err.addCause(cause2);

            % Act
            result = mcpserver.internal.error.ExceptionReport.stripInternalFrames( ...
                err, "someCaller");

            % Assert
            testCase.verifyLength(result.cause, 2, ...
                "Cause chain should be preserved");
            testCase.verifyEqual(result.cause{1}.identifier, 'cause:one');
            testCase.verifyEqual(result.cause{2}.identifier, 'cause:two');
        end
    end

end
